// Copyright 2026 Rungar Authors
// SPDX-License-Identifier: MIT

// Command docgen generates the documentation site's reference pages from the
// code: the command line from the commands, the configuration from the doc
// comments on the types it is read into, and the metrics from those the daemon
// registers.
//
// make docs-gen runs it, and CI checks its committed output is current. A
// configuration field without a doc comment fails it.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
)

// generatedNote heads every generated page's front matter.
const generatedNote = "# Generated by make docs-gen. Do not edit: edit what it is generated from.\n"

func main() {
	out := flag.String("out", "docs/content/docs", "The site's content/docs directory")
	root := flag.String("root", ".", "The module's root, whose packages the configuration is read from")
	flag.Parse()

	steps := []struct {
		name string
		run  func() error
	}{
		{"command line", func() error { return writeCLI(filepath.Join(*out, "reference", "cli")) }},
		{"configuration", func() error { return writeConfiguration(*root, filepath.Join(*out, "reference")) }},
		{"metrics", func() error { return writeMetrics(filepath.Join(*out, "reference")) }},
	}

	for _, step := range steps {
		if err := step.run(); err != nil {
			fmt.Fprintf(os.Stderr, "docgen: %s: %v\n", step.name, err)
			os.Exit(1)
		}
	}
}

// meta is a page's front matter. The description and icon are shown on the
// page's card where another page lists it.
type meta struct {
	title       string
	weight      int
	description string
	icon        string

	// collapsed keeps the page's section closed in the sidebar, for one with
	// too many pages to show open.
	collapsed bool
}

// writePage writes a page with front matter.
func writePage(path string, m meta, body []byte) error {
	var page bytes.Buffer

	page.WriteString("---\n" + generatedNote)
	fmt.Fprintf(&page, "title: %q\n", m.title)
	if m.weight > 0 {
		fmt.Fprintf(&page, "weight: %d\n", m.weight)
	}
	if m.description != "" {
		fmt.Fprintf(&page, "description: %q\n", m.description)
	}
	if m.icon != "" {
		fmt.Fprintf(&page, "icon: %s\n", m.icon)
	}
	if m.collapsed {
		page.WriteString("cascade:\n  - params:\n      sidebar:\n        open: false\n")
	}
	page.WriteString("---\n\n")
	page.Write(bytes.TrimLeft(body, "\n"))

	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		return err
	}

	return os.WriteFile(path, page.Bytes(), 0o600)
}
