// Copyright 2026 Rungar Authors
// SPDX-License-Identifier: MIT

package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
)

// generatedNote heads every generated page's front matter.
const generatedNote = "# Generated by make docs-gen. Do not edit: edit what it is generated from.\n"

// meta is a page's front matter. The description and icon are shown on the
// page's card where another page lists it.
type meta struct {
	title       string
	weight      int
	description string
	icon        string

	// collapsed keeps the page's section closed in the sidebar, for one with
	// too many pages to show open.
	collapsed bool
}

// writePage writes a page with front matter.
func writePage(path string, m meta, body []byte) error {
	var page bytes.Buffer

	page.WriteString("---\n" + generatedNote)
	fmt.Fprintf(&page, "title: %q\n", m.title)
	if m.weight > 0 {
		fmt.Fprintf(&page, "weight: %d\n", m.weight)
	}
	if m.description != "" {
		fmt.Fprintf(&page, "description: %q\n", m.description)
	}
	if m.icon != "" {
		fmt.Fprintf(&page, "icon: %s\n", m.icon)
	}
	if m.collapsed {
		page.WriteString("cascade:\n  - params:\n      sidebar:\n        open: false\n")
	}
	page.WriteString("---\n\n")
	page.Write(bytes.TrimLeft(body, "\n"))

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil { //nolint:gosec // holds public pages
		return err
	}

	// Committed to the repository, and read by whoever builds the site.
	return os.WriteFile(path, page.Bytes(), 0o644)
}
