# Copyright 2026 Rungar Authors
# SPDX-License-Identifier: MIT
{{- if .Values.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rungar.fullname" . }}-metrics
  labels:
    {{- include "rungar.labels" . | nindent 4 }}
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "rungar.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
{{- end }}
