// Copyright 2026 Rungar Authors
// SPDX-License-Identifier: MIT

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: rungar/v1/rungar.proto

package rungarv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RungarService_GetStatus_FullMethodName       = "/rungar.v1.RungarService/GetStatus"
	RungarService_ListScaleSets_FullMethodName   = "/rungar.v1.RungarService/ListScaleSets"
	RungarService_GetScaleSet_FullMethodName     = "/rungar.v1.RungarService/GetScaleSet"
	RungarService_RemoveScaleSet_FullMethodName  = "/rungar.v1.RungarService/RemoveScaleSet"
	RungarService_Reconcile_FullMethodName       = "/rungar.v1.RungarService/Reconcile"
	RungarService_PauseScaleSet_FullMethodName   = "/rungar.v1.RungarService/PauseScaleSet"
	RungarService_ResumeScaleSet_FullMethodName  = "/rungar.v1.RungarService/ResumeScaleSet"
	RungarService_ListProviders_FullMethodName   = "/rungar.v1.RungarService/ListProviders"
	RungarService_GetProvider_FullMethodName     = "/rungar.v1.RungarService/GetProvider"
	RungarService_DisableProvider_FullMethodName = "/rungar.v1.RungarService/DisableProvider"
	RungarService_EnableProvider_FullMethodName  = "/rungar.v1.RungarService/EnableProvider"
	RungarService_ListRunners_FullMethodName     = "/rungar.v1.RungarService/ListRunners"
	RungarService_RemoveRunner_FullMethodName    = "/rungar.v1.RungarService/RemoveRunner"
	RungarService_ListEvents_FullMethodName      = "/rungar.v1.RungarService/ListEvents"
)

// RungarServiceClient is the client API for RungarService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RungarService is a running daemon, as the command line sees it: what it runs
// and what it knows of its scale sets, providers and runners. It is served on
// a Unix socket, whose permissions decide who may use it.
//
// A failed call ends with a status whose code says what kind of failure it
// was, and whose message says it for a person:
//
//   - `NOT_FOUND`: no scale set, provider or runner of that name.
//   - `INVALID_ARGUMENT`: the request is malformed, or asks for something the
//     configuration rules out, such as removing a configured scale set.
//   - `FAILED_PRECONDITION`: the thing is busy: a runner running a job.
//   - `RESOURCE_EXHAUSTED`: no provider has room.
//   - `UNAVAILABLE`: a scale set is still starting, something it needs
//     cannot be reached, or a follower of the events fell behind. Trying
//     again may work.
//   - `CANCELED`, `DEADLINE_EXCEEDED`: the call was cancelled, or ran out of
//     time, before it finished.
//   - `INTERNAL`: anything else: the daemon failed.
//
// A status gRPC itself raises, such as `UNIMPLEMENTED` for a method this
// daemon does not have, arrives as it is.
type RungarServiceClient interface {
	// GetStatus returns everything at once: the daemon, its scale sets, its
	// providers and the runners on them.
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*DaemonStatus, error)
	// ListScaleSets returns the configured scale sets, and those found only by
	// their runners on the fleet, each with what GitHub has of it.
	ListScaleSets(ctx context.Context, in *ListScaleSetsRequest, opts ...grpc.CallOption) (*ListScaleSetsResponse, error)
	// GetScaleSet returns one scale set, configured or not, with what GitHub
	// has of it.
	GetScaleSet(ctx context.Context, in *GetScaleSetRequest, opts ...grpc.CallOption) (*ScaleSet, error)
	// RemoveScaleSet removes a scale set no longer configured: the runners it
	// can, and, once none is left running a job, the scale set on GitHub.
	// Called again, it carries on where it left off.
	RemoveScaleSet(ctx context.Context, in *RemoveScaleSetRequest, opts ...grpc.CallOption) (*RemoveScaleSetResponse, error)
	// Reconcile compares the named scale sets, or every one, with the fleet
	// now, and returns them afterwards.
	Reconcile(ctx context.Context, in *ReconcileRequest, opts ...grpc.CallOption) (*ReconcileResponse, error)
	// PauseScaleSet stops a configured scale set taking jobs, until it is
	// resumed or the daemon restarts: GitHub is told it has no room, no
	// runner is created, its idle runners are removed and its busy ones are
	// left to finish. It returns the scale set.
	PauseScaleSet(ctx context.Context, in *PauseScaleSetRequest, opts ...grpc.CallOption) (*ScaleSet, error)
	// ResumeScaleSet has a paused scale set take jobs again.
	ResumeScaleSet(ctx context.Context, in *ResumeScaleSetRequest, opts ...grpc.CallOption) (*ScaleSet, error)
	// ListProviders returns every provider, in configuration order.
	ListProviders(ctx context.Context, in *ListProvidersRequest, opts ...grpc.CallOption) (*ListProvidersResponse, error)
	// GetProvider returns one provider.
	GetProvider(ctx context.Context, in *GetProviderRequest, opts ...grpc.CallOption) (*Provider, error)
	// DisableProvider takes a provider out of placement, leaving the runners
	// on it to finish, until it is enabled or the daemon restarts.
	DisableProvider(ctx context.Context, in *DisableProviderRequest, opts ...grpc.CallOption) (*Provider, error)
	// EnableProvider puts a provider back into placement.
	EnableProvider(ctx context.Context, in *EnableProviderRequest, opts ...grpc.CallOption) (*Provider, error)
	// ListRunners returns this installation's runners on the fleet.
	ListRunners(ctx context.Context, in *ListRunnersRequest, opts ...grpc.CallOption) (*ListRunnersResponse, error)
	// RemoveRunner removes a runner: its registration first, which GitHub
	// refuses for a runner running a job, then its machine. It returns the
	// runner as it was.
	RemoveRunner(ctx context.Context, in *RemoveRunnerRequest, opts ...grpc.CallOption) (*Runner, error)
	// ListEvents streams what the daemon has done to runners, providers and
	// scale sets: the history kept, oldest first, in batches, then, with
	// follow, each new event as it happens, none missed between the two. A
	// follower that does not keep up is disconnected with UNAVAILABLE rather
	// than slowing the daemon.
	ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListEventsResponse], error)
}

type rungarServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRungarServiceClient(cc grpc.ClientConnInterface) RungarServiceClient {
	return &rungarServiceClient{cc}
}

func (c *rungarServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*DaemonStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DaemonStatus)
	err := c.cc.Invoke(ctx, RungarService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rungarServiceClient) ListScaleSets(ctx context.Context, in *ListScaleSetsRequest, opts ...grpc.CallOption) (*ListScaleSetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListScaleSetsResponse)
	err := c.cc.Invoke(ctx, RungarService_ListScaleSets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rungarServiceClient) GetScaleSet(ctx context.Context, in *GetScaleSetRequest, opts ...grpc.CallOption) (*ScaleSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScaleSet)
	err := c.cc.Invoke(ctx, RungarService_GetScaleSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rungarServiceClient) RemoveScaleSet(ctx context.Context, in *RemoveScaleSetRequest, opts ...grpc.CallOption) (*RemoveScaleSetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveScaleSetResponse)
	err := c.cc.Invoke(ctx, RungarService_RemoveScaleSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rungarServiceClient) Reconcile(ctx context.Context, in *ReconcileRequest, opts ...grpc.CallOption) (*ReconcileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReconcileResponse)
	err := c.cc.Invoke(ctx, RungarService_Reconcile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rungarServiceClient) PauseScaleSet(ctx context.Context, in *PauseScaleSetRequest, opts ...grpc.CallOption) (*ScaleSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScaleSet)
	err := c.cc.Invoke(ctx, RungarService_PauseScaleSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rungarServiceClient) ResumeScaleSet(ctx context.Context, in *ResumeScaleSetRequest, opts ...grpc.CallOption) (*ScaleSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScaleSet)
	err := c.cc.Invoke(ctx, RungarService_ResumeScaleSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rungarServiceClient) ListProviders(ctx context.Context, in *ListProvidersRequest, opts ...grpc.CallOption) (*ListProvidersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProvidersResponse)
	err := c.cc.Invoke(ctx, RungarService_ListProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rungarServiceClient) GetProvider(ctx context.Context, in *GetProviderRequest, opts ...grpc.CallOption) (*Provider, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Provider)
	err := c.cc.Invoke(ctx, RungarService_GetProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rungarServiceClient) DisableProvider(ctx context.Context, in *DisableProviderRequest, opts ...grpc.CallOption) (*Provider, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Provider)
	err := c.cc.Invoke(ctx, RungarService_DisableProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rungarServiceClient) EnableProvider(ctx context.Context, in *EnableProviderRequest, opts ...grpc.CallOption) (*Provider, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Provider)
	err := c.cc.Invoke(ctx, RungarService_EnableProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rungarServiceClient) ListRunners(ctx context.Context, in *ListRunnersRequest, opts ...grpc.CallOption) (*ListRunnersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRunnersResponse)
	err := c.cc.Invoke(ctx, RungarService_ListRunners_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rungarServiceClient) RemoveRunner(ctx context.Context, in *RemoveRunnerRequest, opts ...grpc.CallOption) (*Runner, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Runner)
	err := c.cc.Invoke(ctx, RungarService_RemoveRunner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rungarServiceClient) ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListEventsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RungarService_ServiceDesc.Streams[0], RungarService_ListEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListEventsRequest, ListEventsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RungarService_ListEventsClient = grpc.ServerStreamingClient[ListEventsResponse]

// RungarServiceServer is the server API for RungarService service.
// All implementations should embed UnimplementedRungarServiceServer
// for forward compatibility.
//
// RungarService is a running daemon, as the command line sees it: what it runs
// and what it knows of its scale sets, providers and runners. It is served on
// a Unix socket, whose permissions decide who may use it.
//
// A failed call ends with a status whose code says what kind of failure it
// was, and whose message says it for a person:
//
//   - `NOT_FOUND`: no scale set, provider or runner of that name.
//   - `INVALID_ARGUMENT`: the request is malformed, or asks for something the
//     configuration rules out, such as removing a configured scale set.
//   - `FAILED_PRECONDITION`: the thing is busy: a runner running a job.
//   - `RESOURCE_EXHAUSTED`: no provider has room.
//   - `UNAVAILABLE`: a scale set is still starting, something it needs
//     cannot be reached, or a follower of the events fell behind. Trying
//     again may work.
//   - `CANCELED`, `DEADLINE_EXCEEDED`: the call was cancelled, or ran out of
//     time, before it finished.
//   - `INTERNAL`: anything else: the daemon failed.
//
// A status gRPC itself raises, such as `UNIMPLEMENTED` for a method this
// daemon does not have, arrives as it is.
type RungarServiceServer interface {
	// GetStatus returns everything at once: the daemon, its scale sets, its
	// providers and the runners on them.
	GetStatus(context.Context, *GetStatusRequest) (*DaemonStatus, error)
	// ListScaleSets returns the configured scale sets, and those found only by
	// their runners on the fleet, each with what GitHub has of it.
	ListScaleSets(context.Context, *ListScaleSetsRequest) (*ListScaleSetsResponse, error)
	// GetScaleSet returns one scale set, configured or not, with what GitHub
	// has of it.
	GetScaleSet(context.Context, *GetScaleSetRequest) (*ScaleSet, error)
	// RemoveScaleSet removes a scale set no longer configured: the runners it
	// can, and, once none is left running a job, the scale set on GitHub.
	// Called again, it carries on where it left off.
	RemoveScaleSet(context.Context, *RemoveScaleSetRequest) (*RemoveScaleSetResponse, error)
	// Reconcile compares the named scale sets, or every one, with the fleet
	// now, and returns them afterwards.
	Reconcile(context.Context, *ReconcileRequest) (*ReconcileResponse, error)
	// PauseScaleSet stops a configured scale set taking jobs, until it is
	// resumed or the daemon restarts: GitHub is told it has no room, no
	// runner is created, its idle runners are removed and its busy ones are
	// left to finish. It returns the scale set.
	PauseScaleSet(context.Context, *PauseScaleSetRequest) (*ScaleSet, error)
	// ResumeScaleSet has a paused scale set take jobs again.
	ResumeScaleSet(context.Context, *ResumeScaleSetRequest) (*ScaleSet, error)
	// ListProviders returns every provider, in configuration order.
	ListProviders(context.Context, *ListProvidersRequest) (*ListProvidersResponse, error)
	// GetProvider returns one provider.
	GetProvider(context.Context, *GetProviderRequest) (*Provider, error)
	// DisableProvider takes a provider out of placement, leaving the runners
	// on it to finish, until it is enabled or the daemon restarts.
	DisableProvider(context.Context, *DisableProviderRequest) (*Provider, error)
	// EnableProvider puts a provider back into placement.
	EnableProvider(context.Context, *EnableProviderRequest) (*Provider, error)
	// ListRunners returns this installation's runners on the fleet.
	ListRunners(context.Context, *ListRunnersRequest) (*ListRunnersResponse, error)
	// RemoveRunner removes a runner: its registration first, which GitHub
	// refuses for a runner running a job, then its machine. It returns the
	// runner as it was.
	RemoveRunner(context.Context, *RemoveRunnerRequest) (*Runner, error)
	// ListEvents streams what the daemon has done to runners, providers and
	// scale sets: the history kept, oldest first, in batches, then, with
	// follow, each new event as it happens, none missed between the two. A
	// follower that does not keep up is disconnected with UNAVAILABLE rather
	// than slowing the daemon.
	ListEvents(*ListEventsRequest, grpc.ServerStreamingServer[ListEventsResponse]) error
}

// UnimplementedRungarServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRungarServiceServer struct{}

func (UnimplementedRungarServiceServer) GetStatus(context.Context, *GetStatusRequest) (*DaemonStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedRungarServiceServer) ListScaleSets(context.Context, *ListScaleSetsRequest) (*ListScaleSetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListScaleSets not implemented")
}
func (UnimplementedRungarServiceServer) GetScaleSet(context.Context, *GetScaleSetRequest) (*ScaleSet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScaleSet not implemented")
}
func (UnimplementedRungarServiceServer) RemoveScaleSet(context.Context, *RemoveScaleSetRequest) (*RemoveScaleSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveScaleSet not implemented")
}
func (UnimplementedRungarServiceServer) Reconcile(context.Context, *ReconcileRequest) (*ReconcileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reconcile not implemented")
}
func (UnimplementedRungarServiceServer) PauseScaleSet(context.Context, *PauseScaleSetRequest) (*ScaleSet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PauseScaleSet not implemented")
}
func (UnimplementedRungarServiceServer) ResumeScaleSet(context.Context, *ResumeScaleSetRequest) (*ScaleSet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumeScaleSet not implemented")
}
func (UnimplementedRungarServiceServer) ListProviders(context.Context, *ListProvidersRequest) (*ListProvidersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProviders not implemented")
}
func (UnimplementedRungarServiceServer) GetProvider(context.Context, *GetProviderRequest) (*Provider, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProvider not implemented")
}
func (UnimplementedRungarServiceServer) DisableProvider(context.Context, *DisableProviderRequest) (*Provider, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableProvider not implemented")
}
func (UnimplementedRungarServiceServer) EnableProvider(context.Context, *EnableProviderRequest) (*Provider, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnableProvider not implemented")
}
func (UnimplementedRungarServiceServer) ListRunners(context.Context, *ListRunnersRequest) (*ListRunnersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRunners not implemented")
}
func (UnimplementedRungarServiceServer) RemoveRunner(context.Context, *RemoveRunnerRequest) (*Runner, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveRunner not implemented")
}
func (UnimplementedRungarServiceServer) ListEvents(*ListEventsRequest, grpc.ServerStreamingServer[ListEventsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ListEvents not implemented")
}
func (UnimplementedRungarServiceServer) testEmbeddedByValue() {}

// UnsafeRungarServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RungarServiceServer will
// result in compilation errors.
type UnsafeRungarServiceServer interface {
	mustEmbedUnimplementedRungarServiceServer()
}

func RegisterRungarServiceServer(s grpc.ServiceRegistrar, srv RungarServiceServer) {
	// If the following call pancis, it indicates UnimplementedRungarServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RungarService_ServiceDesc, srv)
}

func _RungarService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RungarServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RungarService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RungarServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RungarService_ListScaleSets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListScaleSetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RungarServiceServer).ListScaleSets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RungarService_ListScaleSets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RungarServiceServer).ListScaleSets(ctx, req.(*ListScaleSetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RungarService_GetScaleSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScaleSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RungarServiceServer).GetScaleSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RungarService_GetScaleSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RungarServiceServer).GetScaleSet(ctx, req.(*GetScaleSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RungarService_RemoveScaleSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveScaleSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RungarServiceServer).RemoveScaleSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RungarService_RemoveScaleSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RungarServiceServer).RemoveScaleSet(ctx, req.(*RemoveScaleSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RungarService_Reconcile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReconcileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RungarServiceServer).Reconcile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RungarService_Reconcile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RungarServiceServer).Reconcile(ctx, req.(*ReconcileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RungarService_PauseScaleSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseScaleSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RungarServiceServer).PauseScaleSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RungarService_PauseScaleSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RungarServiceServer).PauseScaleSet(ctx, req.(*PauseScaleSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RungarService_ResumeScaleSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeScaleSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RungarServiceServer).ResumeScaleSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RungarService_ResumeScaleSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RungarServiceServer).ResumeScaleSet(ctx, req.(*ResumeScaleSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RungarService_ListProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RungarServiceServer).ListProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RungarService_ListProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RungarServiceServer).ListProviders(ctx, req.(*ListProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RungarService_GetProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RungarServiceServer).GetProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RungarService_GetProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RungarServiceServer).GetProvider(ctx, req.(*GetProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RungarService_DisableProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RungarServiceServer).DisableProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RungarService_DisableProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RungarServiceServer).DisableProvider(ctx, req.(*DisableProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RungarService_EnableProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RungarServiceServer).EnableProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RungarService_EnableProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RungarServiceServer).EnableProvider(ctx, req.(*EnableProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RungarService_ListRunners_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRunnersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RungarServiceServer).ListRunners(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RungarService_ListRunners_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RungarServiceServer).ListRunners(ctx, req.(*ListRunnersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RungarService_RemoveRunner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRunnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RungarServiceServer).RemoveRunner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RungarService_RemoveRunner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RungarServiceServer).RemoveRunner(ctx, req.(*RemoveRunnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RungarService_ListEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RungarServiceServer).ListEvents(m, &grpc.GenericServerStream[ListEventsRequest, ListEventsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RungarService_ListEventsServer = grpc.ServerStreamingServer[ListEventsResponse]

// RungarService_ServiceDesc is the grpc.ServiceDesc for RungarService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RungarService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rungar.v1.RungarService",
	HandlerType: (*RungarServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _RungarService_GetStatus_Handler,
		},
		{
			MethodName: "ListScaleSets",
			Handler:    _RungarService_ListScaleSets_Handler,
		},
		{
			MethodName: "GetScaleSet",
			Handler:    _RungarService_GetScaleSet_Handler,
		},
		{
			MethodName: "RemoveScaleSet",
			Handler:    _RungarService_RemoveScaleSet_Handler,
		},
		{
			MethodName: "Reconcile",
			Handler:    _RungarService_Reconcile_Handler,
		},
		{
			MethodName: "PauseScaleSet",
			Handler:    _RungarService_PauseScaleSet_Handler,
		},
		{
			MethodName: "ResumeScaleSet",
			Handler:    _RungarService_ResumeScaleSet_Handler,
		},
		{
			MethodName: "ListProviders",
			Handler:    _RungarService_ListProviders_Handler,
		},
		{
			MethodName: "GetProvider",
			Handler:    _RungarService_GetProvider_Handler,
		},
		{
			MethodName: "DisableProvider",
			Handler:    _RungarService_DisableProvider_Handler,
		},
		{
			MethodName: "EnableProvider",
			Handler:    _RungarService_EnableProvider_Handler,
		},
		{
			MethodName: "ListRunners",
			Handler:    _RungarService_ListRunners_Handler,
		},
		{
			MethodName: "RemoveRunner",
			Handler:    _RungarService_RemoveRunner_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEvents",
			Handler:       _RungarService_ListEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rungar/v1/rungar.proto",
}
