// Copyright 2026 Rungar Authors
// SPDX-License-Identifier: MIT

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: rungar/v1/rungar.proto

package rungarv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ScaleSetPhase is how far a configured scale set is from taking jobs.
type ScaleSetPhase int32

const (
	ScaleSetPhase_SCALE_SET_PHASE_UNSPECIFIED ScaleSetPhase = 0
	// Being looked up or created on GitHub, and its runners adopted.
	ScaleSetPhase_SCALE_SET_PHASE_STARTING ScaleSetPhase = 1
	// Waiting for another daemon's message session on it to end.
	ScaleSetPhase_SCALE_SET_PHASE_WAITING_FOR_SESSION ScaleSetPhase = 2
	// Taking jobs.
	ScaleSetPhase_SCALE_SET_PHASE_LISTENING ScaleSetPhase = 3
)

// Enum value maps for ScaleSetPhase.
var (
	ScaleSetPhase_name = map[int32]string{
		0: "SCALE_SET_PHASE_UNSPECIFIED",
		1: "SCALE_SET_PHASE_STARTING",
		2: "SCALE_SET_PHASE_WAITING_FOR_SESSION",
		3: "SCALE_SET_PHASE_LISTENING",
	}
	ScaleSetPhase_value = map[string]int32{
		"SCALE_SET_PHASE_UNSPECIFIED":         0,
		"SCALE_SET_PHASE_STARTING":            1,
		"SCALE_SET_PHASE_WAITING_FOR_SESSION": 2,
		"SCALE_SET_PHASE_LISTENING":           3,
	}
)

func (x ScaleSetPhase) Enum() *ScaleSetPhase {
	p := new(ScaleSetPhase)
	*p = x
	return p
}

func (x ScaleSetPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScaleSetPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_rungar_v1_rungar_proto_enumTypes[0].Descriptor()
}

func (ScaleSetPhase) Type() protoreflect.EnumType {
	return &file_rungar_v1_rungar_proto_enumTypes[0]
}

func (x ScaleSetPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScaleSetPhase.Descriptor instead.
func (ScaleSetPhase) EnumDescriptor() ([]byte, []int) {
	return file_rungar_v1_rungar_proto_rawDescGZIP(), []int{0}
}

// RunnerState is what the daemon knows a runner to be doing.
type RunnerState int32

const (
	RunnerState_RUNNER_STATE_UNSPECIFIED RunnerState = 0
	// Made, and not yet connected to GitHub.
	RunnerState_RUNNER_STATE_STARTING RunnerState = 1
	// Connected, and waiting for a job.
	RunnerState_RUNNER_STATE_IDLE RunnerState = 2
	// Running a job.
	RunnerState_RUNNER_STATE_BUSY RunnerState = 3
)

// Enum value maps for RunnerState.
var (
	RunnerState_name = map[int32]string{
		0: "RUNNER_STATE_UNSPECIFIED",
		1: "RUNNER_STATE_STARTING",
		2: "RUNNER_STATE_IDLE",
		3: "RUNNER_STATE_BUSY",
	}
	RunnerState_value = map[string]int32{
		"RUNNER_STATE_UNSPECIFIED": 0,
		"RUNNER_STATE_STARTING":    1,
		"RUNNER_STATE_IDLE":        2,
		"RUNNER_STATE_BUSY":        3,
	}
)

func (x RunnerState) Enum() *RunnerState {
	p := new(RunnerState)
	*p = x
	return p
}

func (x RunnerState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunnerState) Descriptor() protoreflect.EnumDescriptor {
	return file_rungar_v1_rungar_proto_enumTypes[1].Descriptor()
}

func (RunnerState) Type() protoreflect.EnumType {
	return &file_rungar_v1_rungar_proto_enumTypes[1]
}

func (x RunnerState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RunnerState.Descriptor instead.
func (RunnerState) EnumDescriptor() ([]byte, []int) {
	return file_rungar_v1_rungar_proto_rawDescGZIP(), []int{1}
}

// RunnerRegistration is what GitHub says of a runner.
type RunnerGitHubStatus int32

const (
	RunnerGitHubStatus_RUNNER_GIT_HUB_STATUS_UNSPECIFIED RunnerGitHubStatus = 0
	// Registered, and running a job.
	RunnerGitHubStatus_RUNNER_GIT_HUB_STATUS_BUSY RunnerGitHubStatus = 1
	// Registered, connected and waiting.
	RunnerGitHubStatus_RUNNER_GIT_HUB_STATUS_IDLE RunnerGitHubStatus = 2
	// Registered, and not connected.
	RunnerGitHubStatus_RUNNER_GIT_HUB_STATUS_OFFLINE RunnerGitHubStatus = 3
	// GitHub has no runner of that name.
	RunnerGitHubStatus_RUNNER_GIT_HUB_STATUS_NOT_REGISTERED RunnerGitHubStatus = 4
)

// Enum value maps for RunnerGitHubStatus.
var (
	RunnerGitHubStatus_name = map[int32]string{
		0: "RUNNER_GIT_HUB_STATUS_UNSPECIFIED",
		1: "RUNNER_GIT_HUB_STATUS_BUSY",
		2: "RUNNER_GIT_HUB_STATUS_IDLE",
		3: "RUNNER_GIT_HUB_STATUS_OFFLINE",
		4: "RUNNER_GIT_HUB_STATUS_NOT_REGISTERED",
	}
	RunnerGitHubStatus_value = map[string]int32{
		"RUNNER_GIT_HUB_STATUS_UNSPECIFIED":    0,
		"RUNNER_GIT_HUB_STATUS_BUSY":           1,
		"RUNNER_GIT_HUB_STATUS_IDLE":           2,
		"RUNNER_GIT_HUB_STATUS_OFFLINE":        3,
		"RUNNER_GIT_HUB_STATUS_NOT_REGISTERED": 4,
	}
)

func (x RunnerGitHubStatus) Enum() *RunnerGitHubStatus {
	p := new(RunnerGitHubStatus)
	*p = x
	return p
}

func (x RunnerGitHubStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunnerGitHubStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_rungar_v1_rungar_proto_enumTypes[2].Descriptor()
}

func (RunnerGitHubStatus) Type() protoreflect.EnumType {
	return &file_rungar_v1_rungar_proto_enumTypes[2]
}

func (x RunnerGitHubStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RunnerGitHubStatus.Descriptor instead.
func (RunnerGitHubStatus) EnumDescriptor() ([]byte, []int) {
	return file_rungar_v1_rungar_proto_rawDescGZIP(), []int{2}
}

// EventKind is the kind of thing an event is about.
type EventKind int32

const (
	EventKind_EVENT_KIND_UNSPECIFIED EventKind = 0
	EventKind_EVENT_KIND_RUNNER      EventKind = 1
	EventKind_EVENT_KIND_PROVIDER    EventKind = 2
	EventKind_EVENT_KIND_SCALE_SET   EventKind = 3
)

// Enum value maps for EventKind.
var (
	EventKind_name = map[int32]string{
		0: "EVENT_KIND_UNSPECIFIED",
		1: "EVENT_KIND_RUNNER",
		2: "EVENT_KIND_PROVIDER",
		3: "EVENT_KIND_SCALE_SET",
	}
	EventKind_value = map[string]int32{
		"EVENT_KIND_UNSPECIFIED": 0,
		"EVENT_KIND_RUNNER":      1,
		"EVENT_KIND_PROVIDER":    2,
		"EVENT_KIND_SCALE_SET":   3,
	}
)

func (x EventKind) Enum() *EventKind {
	p := new(EventKind)
	*p = x
	return p
}

func (x EventKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventKind) Descriptor() protoreflect.EnumDescriptor {
	return file_rungar_v1_rungar_proto_enumTypes[3].Descriptor()
}

func (EventKind) Type() protoreflect.EnumType {
	return &file_rungar_v1_rungar_proto_enumTypes[3]
}

func (x EventKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventKind.Descriptor instead.
func (EventKind) EnumDescriptor() ([]byte, []int) {
	return file_rungar_v1_rungar_proto_rawDescGZIP(), []int{3}
}

// EventAction is what happened to it.
type EventAction int32

const (
	EventAction_EVENT_ACTION_UNSPECIFIED EventAction = 0
	// A runner made by the daemon.
	EventAction_EVENT_ACTION_CREATED EventAction = 1
	// A runner found on the fleet: left by an earlier daemon, or missed.
	EventAction_EVENT_ACTION_ADOPTED EventAction = 2
	// A runner whose machine was removed.
	EventAction_EVENT_ACTION_REMOVED EventAction = 3
	// A runner forgotten without its machine being removed: the machine
	// went, or its provider stopped answering.
	EventAction_EVENT_ACTION_LOST EventAction = 4
	// A provider a scale set found full, which it skips for a while, trying
	// its next provider meanwhile.
	EventAction_EVENT_ACTION_FULL EventAction = 6
	// A provider that failed to make a scale set's runner, which it skips
	// for a while, trying its next provider meanwhile.
	EventAction_EVENT_ACTION_FAILING EventAction = 8
	// A scale set paused: taking no jobs, and making no runners.
	EventAction_EVENT_ACTION_PAUSED EventAction = 9
	// A paused scale set resumed: taking jobs again.
	EventAction_EVENT_ACTION_RESUMED EventAction = 10
)

// Enum value maps for EventAction.
var (
	EventAction_name = map[int32]string{
		0:  "EVENT_ACTION_UNSPECIFIED",
		1:  "EVENT_ACTION_CREATED",
		2:  "EVENT_ACTION_ADOPTED",
		3:  "EVENT_ACTION_REMOVED",
		4:  "EVENT_ACTION_LOST",
		6:  "EVENT_ACTION_FULL",
		8:  "EVENT_ACTION_FAILING",
		9:  "EVENT_ACTION_PAUSED",
		10: "EVENT_ACTION_RESUMED",
	}
	EventAction_value = map[string]int32{
		"EVENT_ACTION_UNSPECIFIED": 0,
		"EVENT_ACTION_CREATED":     1,
		"EVENT_ACTION_ADOPTED":     2,
		"EVENT_ACTION_REMOVED":     3,
		"EVENT_ACTION_LOST":        4,
		"EVENT_ACTION_FULL":        6,
		"EVENT_ACTION_FAILING":     8,
		"EVENT_ACTION_PAUSED":      9,
		"EVENT_ACTION_RESUMED":     10,
	}
)

func (x EventAction) Enum() *EventAction {
	p := new(EventAction)
	*p = x
	return p
}

func (x EventAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventAction) Descriptor() protoreflect.EnumDescriptor {
	return file_rungar_v1_rungar_proto_enumTypes[4].Descriptor()
}

func (EventAction) Type() protoreflect.EnumType {
	return &file_rungar_v1_rungar_proto_enumTypes[4]
}

func (x EventAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventAction.Descriptor instead.
func (EventAction) EnumDescriptor() ([]byte, []int) {
	return file_rungar_v1_rungar_proto_rawDescGZIP(), []int{4}
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_rungar_v1_rungar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rungar_v1_rungar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_rungar_v1_rungar_proto_rawDescGZIP(), []int{0}
}

// Status is the daemon and everything it runs.
type DaemonStatus struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Daemon *Daemon                `protobuf:"bytes,1,opt,name=daemon,proto3" json:"daemon,omitempty"`
	// The configured scale sets, in configuration order. What GitHub has of
	// each is not asked for: see ListScaleSets.
	ScaleSets []*ScaleSet `protobuf:"bytes,2,rep,name=scale_sets,json=scaleSets,proto3" json:"scale_sets,omitempty"`
	// The providers, in configuration order.
	Providers []*Provider `protobuf:"bytes,3,rep,name=providers,proto3" json:"providers,omitempty"`
	// The installation's runners on the fleet.
	Runners []*Runner `protobuf:"bytes,4,rep,name=runners,proto3" json:"runners,omitempty"`
	// Providers that could not be listed, by name, with why: their runners
	// are missing from runners.
	UnreachableProviders map[string]string `protobuf:"bytes,5,rep,name=unreachable_providers,json=unreachableProviders,proto3" json:"unreachable_providers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DaemonStatus) Reset() {
	*x = DaemonStatus{}
	mi := &file_rungar_v1_rungar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonStatus) ProtoMessage() {}

func (x *DaemonStatus) ProtoReflect() protoreflect.Message {
	mi := &file_rungar_v1_rungar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonStatus.ProtoReflect.Descriptor instead.
func (*DaemonStatus) Descriptor() ([]byte, []int) {
	return file_rungar_v1_rungar_proto_rawDescGZIP(), []int{1}
}

func (x *DaemonStatus) GetDaemon() *Daemon {
	if x != nil {
		return x.Daemon
	}
	return nil
}

func (x *DaemonStatus) GetScaleSets() []*ScaleSet {
	if x != nil {
		return x.ScaleSets
	}
	return nil
}

func (x *DaemonStatus) GetProviders() []*Provider {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *DaemonStatus) GetRunners() []*Runner {
	if x != nil {
		return x.Runners
	}
	return nil
}

func (x *DaemonStatus) GetUnreachableProviders() map[string]string {
	if x != nil {
		return x.UnreachableProviders
	}
	return nil
}

// Daemon is the running daemon.
type Daemon struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Commit  string                 `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	// When the process started, and the configuration it runs from was
	// loaded.
	StartTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// The configuration file it runs from.
	ConfigFile string `protobuf:"bytes,5,opt,name=config_file,json=configFile,proto3" json:"config_file,omitempty"`
	// What this installation is called, and put on every runner.
	Installation  string  `protobuf:"bytes,6,opt,name=installation,proto3" json:"installation,omitempty"`
	Github        *GitHub `protobuf:"bytes,7,opt,name=github,proto3" json:"github,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Daemon) Reset() {
	*x = Daemon{}
	mi := &file_rungar_v1_rungar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Daemon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Daemon) ProtoMessage() {}

func (x *Daemon) ProtoReflect() protoreflect.Message {
	mi := &file_rungar_v1_rungar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Daemon.ProtoReflect.Descriptor instead.
func (*Daemon) Descriptor() ([]byte, []int) {
	return file_rungar_v1_rungar_proto_rawDescGZIP(), []int{2}
}

func (x *Daemon) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Daemon) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *Daemon) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Daemon) GetConfigFile() string {
	if x != nil {
		return x.ConfigFile
	}
	return ""
}

func (x *Daemon) GetInstallation() string {
	if x != nil {
		return x.Installation
	}
	return ""
}

func (x *Daemon) GetGithub() *GitHub {
	if x != nil {
		return x.Github
	}
	return nil
}

// GitHub is where the scale sets live and how the daemon authenticates.
type GitHub struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The enterprise, organisation or repository URL.
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// What url names: repository, organisation or enterprise.
	Scope string `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	// How the daemon authenticates, with nothing secret in it.
	Credentials string `protobuf:"bytes,3,opt,name=credentials,proto3" json:"credentials,omitempty"`
	// Why GitHub did not answer the daemon with them when the status was
	// asked: its refusal, or why it could not be reached. Empty when it
	// answered.
	CredentialsError string `protobuf:"bytes,4,opt,name=credentials_error,json=credentialsError,proto3" json:"credentials_error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GitHub) Reset() {
	*x = GitHub{}
	mi := &file_rungar_v1_rungar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitHub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitHub) ProtoMessage() {}

func (x *GitHub) ProtoReflect() protoreflect.Message {
	mi := &file_rungar_v1_rungar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitHub.ProtoReflect.Descriptor instead.
func (*GitHub) Descriptor() ([]byte, []int) {
	return file_rungar_v1_rungar_proto_rawDescGZIP(), []int{3}
}

func (x *GitHub) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GitHub) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *GitHub) GetCredentials() string {
	if x != nil {
		return x.Credentials
	}
	return ""
}

func (x *GitHub) GetCredentialsError() string {
	if x != nil {
		return x.CredentialsError
	}
	return ""
}

type ListScaleSetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScaleSetsRequest) Reset() {
	*x = ListScaleSetsRequest{}
	mi := &file_rungar_v1_rungar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScaleSetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScaleSetsRequest) ProtoMessage() {}

func (x *ListScaleSetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rungar_v1_rungar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScaleSetsRequest.ProtoReflect.Descriptor instead.
func (*ListScaleSetsRequest) Descriptor() ([]byte, []int) {
	return file_rungar_v1_rungar_proto_rawDescGZIP(), []int{4}
}

type ListScaleSetsResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ScaleSets []*ScaleSet            `protobuf:"bytes,1,rep,name=scale_sets,json=scaleSets,proto3" json:"scale_sets,omitempty"`
	// Providers that could not be listed, by name, with why: a scale set whose
	// only runners are on one is missing, and runner counts are short.
	UnreachableProviders map[string]string `protobuf:"bytes,2,rep,name=unreachable_providers,json=unreachableProviders,proto3" json:"unreachable_providers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ListScaleSetsResponse) Reset() {
	*x = ListScaleSetsResponse{}
	mi := &file_rungar_v1_rungar_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScaleSetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScaleSetsResponse) ProtoMessage() {}

func (x *ListScaleSetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rungar_v1_rungar_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScaleSetsResponse.ProtoReflect.Descriptor instead.
func (*ListScaleSetsResponse) Descriptor() ([]byte, []int) {
	return file_rungar_v1_rungar_proto_rawDescGZIP(), []int{5}
}

func (x *ListScaleSetsResponse) GetScaleSets() []*ScaleSet {
	if x != nil {
		return x.ScaleSets
	}
	return nil
}

func (x *ListScaleSetsResponse) GetUnreachableProviders() map[string]string {
	if x != nil {
		return x.UnreachableProviders
	}
	return nil
}

type GetScaleSetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The runner group to look for it in on GitHub. Empty is the configured
	// one, or Default.
	RunnerGroup   string `protobuf:"bytes,2,opt,name=runner_group,json=runnerGroup,proto3" json:"runner_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScaleSetRequest) Reset() {
	*x = GetScaleSetRequest{}
	mi := &file_rungar_v1_rungar_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScaleSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScaleSetRequest) ProtoMessage() {}

func (x *GetScaleSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rungar_v1_rungar_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScaleSetRequest.ProtoReflect.Descriptor instead.
func (*GetScaleSetRequest) Descriptor() ([]byte, []int) {
	return file_rungar_v1_rungar_proto_rawDescGZIP(), []int{6}
}

func (x *GetScaleSetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetScaleSetRequest) GetRunnerGroup() string {
	if x != nil {
		return x.RunnerGroup
	}
	return ""
}

// ScaleSet is one scale set: what the configuration says of it, what the
// daemon is doing with it, and what GitHub has of it.
type ScaleSet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Whether the configuration has it.
	Configured bool `protobuf:"varint,2,opt,name=configured,proto3" json:"configured,omitempty"`
	// Every label workflows may target it by, its name first.
	Labels []string `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty"`
	// Its providers, in its order.
	Providers []string `protobuf:"bytes,4,rep,name=providers,proto3" json:"providers,omitempty"`
	// spread or pack.
	Placement string `protobuf:"bytes,5,opt,name=placement,proto3" json:"placement,omitempty"`
	// What each of its providers makes of its runner block, in its order.
	RunnerSizes []*RunnerSize `protobuf:"bytes,6,rep,name=runner_sizes,json=runnerSizes,proto3" json:"runner_sizes,omitempty"`
	MinRunners  int32         `protobuf:"varint,7,opt,name=min_runners,json=minRunners,proto3" json:"min_runners,omitempty"`
	MaxRunners  int32         `protobuf:"varint,8,opt,name=max_runners,json=maxRunners,proto3" json:"max_runners,omitempty"`
	Priority    int32         `protobuf:"varint,9,opt,name=priority,proto3" json:"priority,omitempty"`
	RunnerGroup string        `protobuf:"bytes,10,opt,name=runner_group,json=runnerGroup,proto3" json:"runner_group,omitempty"`
	// The runs-on line that targets it, as a workflow writes it.
	RunsOn string        `protobuf:"bytes,11,opt,name=runs_on,json=runsOn,proto3" json:"runs_on,omitempty"`
	Phase  ScaleSetPhase `protobuf:"varint,12,opt,name=phase,proto3,enum=rungar.v1.ScaleSetPhase" json:"phase,omitempty"`
	// How many runners GitHub's latest statistics call for.
	DesiredRunners int32 `protobuf:"varint,13,opt,name=desired_runners,json=desiredRunners,proto3" json:"desired_runners,omitempty"`
	// Its runners the daemon knows of, by state.
	RunnerCounts *RunnerCounts `protobuf:"bytes,14,opt,name=runner_counts,json=runnerCounts,proto3" json:"runner_counts,omitempty"`
	// Why it is holding back from placing a runner, if it is: a scale set of
	// higher priority on one of its providers is waiting for room.
	HoldingBackReason string `protobuf:"bytes,15,opt,name=holding_back_reason,json=holdingBackReason,proto3" json:"holding_back_reason,omitempty"`
	// How many of its runners are on the fleet, as the providers list them.
	FleetRunners int32 `protobuf:"varint,16,opt,name=fleet_runners,json=fleetRunners,proto3" json:"fleet_runners,omitempty"`
	// What GitHub has of it. Absent from GetStatus, which does not ask.
	Github *GitHubScaleSet `protobuf:"bytes,17,opt,name=github,proto3" json:"github,omitempty"`
	// Whether it is paused now: taking no jobs, making no runners.
	Paused bool `protobuf:"varint,18,opt,name=paused,proto3" json:"paused,omitempty"`
	// Whether the configuration has it paused. Where this differs from
	// paused, it was paused or resumed while the daemon ran, and goes back to
	// this when the daemon restarts.
	ConfiguredPaused bool `protobuf:"varint,19,opt,name=configured_paused,json=configuredPaused,proto3" json:"configured_paused,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ScaleSet) Reset() {
	*x = ScaleSet{}
	mi := &file_rungar_v1_rungar_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScaleSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScaleSet) ProtoMessage() {}

func (x *ScaleSet) ProtoReflect() protoreflect.Message {
	mi := &file_rungar_v1_rungar_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScaleSet.ProtoReflect.Descriptor instead.
func (*ScaleSet) Descriptor() ([]byte, []int) {
	return file_rungar_v1_rungar_proto_rawDescGZIP(), []int{7}
}

func (x *ScaleSet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScaleSet) GetConfigured() bool {
	if x != nil {
		return x.Configured
	}
	return false
}

func (x *ScaleSet) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ScaleSet) GetProviders() []string {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *ScaleSet) GetPlacement() string {
	if x != nil {
		return x.Placement
	}
	return ""
}

func (x *ScaleSet) GetRunnerSizes() []*RunnerSize {
	if x != nil {
		return x.RunnerSizes
	}
	return nil
}

func (x *ScaleSet) GetMinRunners() int32 {
	if x != nil {
		return x.MinRunners
	}
	return 0
}

func (x *ScaleSet) GetMaxRunners() int32 {
	if x != nil {
		return x.MaxRunners
	}
	return 0
}

func (x *ScaleSet) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *ScaleSet) GetRunnerGroup() string {
	if x != nil {
		return x.RunnerGroup
	}
	return ""
}

func (x *ScaleSet) GetRunsOn() string {
	if x != nil {
		return x.RunsOn
	}
	return ""
}

func (x *ScaleSet) GetPhase() ScaleSetPhase {
	if x != nil {
		return x.Phase
	}
	return ScaleSetPhase_SCALE_SET_PHASE_UNSPECIFIED
}

func (x *ScaleSet) GetDesiredRunners() int32 {
	if x != nil {
		return x.DesiredRunners
	}
	return 0
}

func (x *ScaleSet) GetRunnerCounts() *RunnerCounts {
	if x != nil {
		return x.RunnerCounts
	}
	return nil
}

func (x *ScaleSet) GetHoldingBackReason() string {
	if x != nil {
		return x.HoldingBackReason
	}
	return ""
}

func (x *ScaleSet) GetFleetRunners() int32 {
	if x != nil {
		return x.FleetRunners
	}
	return 0
}

func (x *ScaleSet) GetGithub() *GitHubScaleSet {
	if x != nil {
		return x.Github
	}
	return nil
}

func (x *ScaleSet) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

func (x *ScaleSet) GetConfiguredPaused() bool {
	if x != nil {
		return x.ConfiguredPaused
	}
	return false
}

// RunnerSize is what one provider makes of a scale set's runner block.
type RunnerSize struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Provider string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	// How big the runner is, as its provider describes it: "4 vCPU, 8 GiB",
	// or a cloud's machine type.
	Description   string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunnerSize) Reset() {
	*x = RunnerSize{}
	mi := &file_rungar_v1_rungar_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunnerSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunnerSize) ProtoMessage() {}

func (x *RunnerSize) ProtoReflect() protoreflect.Message {
	mi := &file_rungar_v1_rungar_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunnerSize.ProtoReflect.Descriptor instead.
func (*RunnerSize) Descriptor() ([]byte, []int) {
	return file_rungar_v1_rungar_proto_rawDescGZIP(), []int{8}
}

func (x *RunnerSize) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *RunnerSize) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// RunnerCounts are runners by what they are doing.
type RunnerCounts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Starting      int32                  `protobuf:"varint,1,opt,name=starting,proto3" json:"starting,omitempty"`
	Idle          int32                  `protobuf:"varint,2,opt,name=idle,proto3" json:"idle,omitempty"`
	Busy          int32                  `protobuf:"varint,3,opt,name=busy,proto3" json:"busy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunnerCounts) Reset() {
	*x = RunnerCounts{}
	mi := &file_rungar_v1_rungar_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunnerCounts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunnerCounts) ProtoMessage() {}

func (x *RunnerCounts) ProtoReflect() protoreflect.Message {
	mi := &file_rungar_v1_rungar_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunnerCounts.ProtoReflect.Descriptor instead.
func (*RunnerCounts) Descriptor() ([]byte, []int) {
	return file_rungar_v1_rungar_proto_rawDescGZIP(), []int{9}
}

func (x *RunnerCounts) GetStarting() int32 {
	if x != nil {
		return x.Starting
	}
	return 0
}

func (x *RunnerCounts) GetIdle() int32 {
	if x != nil {
		return x.Idle
	}
	return 0
}

func (x *RunnerCounts) GetBusy() int32 {
	if x != nil {
		return x.Busy
	}
	return 0
}

// GitHubScaleSet is what GitHub has of a scale set.
type GitHubScaleSet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether GitHub has one of that name in the runner group it was looked
	// for in.
	Found bool `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	// Why GitHub could not be asked, if it could not.
	Error       string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Id          int64  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	RunnerGroup string `protobuf:"bytes,4,opt,name=runner_group,json=runnerGroup,proto3" json:"runner_group,omitempty"`
	// The labels GitHub keeps for it, which it never changes once made.
	Labels        []string               `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Statistics    *ScaleSetStatistics    `protobuf:"bytes,7,opt,name=statistics,proto3" json:"statistics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitHubScaleSet) Reset() {
	*x = GitHubScaleSet{}
	mi := &file_rungar_v1_rungar_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitHubScaleSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitHubScaleSet) ProtoMessage() {}

func (x *GitHubScaleSet) ProtoReflect() protoreflect.Message {
	mi := &file_rungar_v1_rungar_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitHubScaleSet.ProtoReflect.Descriptor instead.
func (*GitHubScaleSet) Descriptor() ([]byte, []int) {
	return file_rungar_v1_rungar_proto_rawDescGZIP(), []int{10}
}

func (x *GitHubScaleSet) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GitHubScaleSet) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GitHubScaleSet) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GitHubScaleSet) GetRunnerGroup() string {
	if x != nil {
		return x.RunnerGroup
	}
	return ""
}

func (x *GitHubScaleSet) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *GitHubScaleSet) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *GitHubScaleSet) GetStatistics() *ScaleSetStatistics {
	if x != nil {
		return x.Statistics
	}
	return nil
}

// ScaleSetStatistics are GitHub's numbers for a scale set.
type ScaleSetStatistics struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AssignedJobs      int32                  `protobuf:"varint,1,opt,name=assigned_jobs,json=assignedJobs,proto3" json:"assigned_jobs,omitempty"`
	RunningJobs       int32                  `protobuf:"varint,2,opt,name=running_jobs,json=runningJobs,proto3" json:"running_jobs,omitempty"`
	RegisteredRunners int32                  `protobuf:"varint,3,opt,name=registered_runners,json=registeredRunners,proto3" json:"registered_runners,omitempty"`
	BusyRunners       int32                  `protobuf:"varint,4,opt,name=busy_runners,json=busyRunners,proto3" json:"busy_runners,omitempty"`
	IdleRunners       int32                  `protobuf:"varint,5,opt,name=idle_runners,json=idleRunners,proto3" json:"idle_runners,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ScaleSetStatistics) Reset() {
	*x = ScaleSetStatistics{}
	mi := &file_rungar_v1_rungar_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScaleSetStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScaleSetStatistics) ProtoMessage() {}

func (x *ScaleSetStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_rungar_v1_rungar_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScaleSetStatistics.ProtoReflect.Descriptor instead.
func (*ScaleSetStatistics) Descriptor() ([]byte, []int) {
	return file_rungar_v1_rungar_proto_rawDescGZIP(), []int{11}
}

func (x *ScaleSetStatistics) GetAssignedJobs() int32 {
	if x != nil {
		return x.AssignedJobs
	}
	return 0
}

func (x *ScaleSetStatistics) GetRunningJobs() int32 {
	if x != nil {
		return x.RunningJobs
	}
	return 0
}

func (x *ScaleSetStatistics) GetRegisteredRunners() int32 {
	if x != nil {
		return x.RegisteredRunners
	}
	return 0
}

func (x *ScaleSetStatistics) GetBusyRunners() int32 {
	if x != nil {
		return x.BusyRunners
	}
	return 0
}

func (x *ScaleSetStatistics) GetIdleRunners() int32 {
	if x != nil {
		return x.IdleRunners
	}
	return 0
}

type DeleteScaleSetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The runner group it is in on GitHub. Empty is Default.
	RunnerGroup   string `protobuf:"bytes,2,opt,name=runner_group,json=runnerGroup,proto3" json:"runner_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScaleSetRequest) Reset() {
	*x = DeleteScaleSetRequest{}
	mi := &file_rungar_v1_rungar_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScaleSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScaleSetRequest) ProtoMessage() {}

func (x *DeleteScaleSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rungar_v1_rungar_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScaleSetRequest.ProtoReflect.Descriptor instead.
func (*DeleteScaleSetRequest) Descriptor() ([]byte, []int) {
	return file_rungar_v1_rungar_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteScaleSetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteScaleSetRequest) GetRunnerGroup() string {
	if x != nil {
		return x.RunnerGroup
	}
	return ""
}

// DeleteScaleSetResponse is what one DeleteScaleSet did.
type DeleteScaleSetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The runners removed.
	Removed []*Runner `protobuf:"bytes,1,rep,name=removed,proto3" json:"removed,omitempty"`
	// How many runners are running jobs, and were left to finish them. While
	// any is, the scale set is left on GitHub.
	BusyLeft int32 `protobuf:"varint,2,opt,name=busy_left,json=busyLeft,proto3" json:"busy_left,omitempty"`
	// The ID of the scale set removed from GitHub, or 0 when it was not: some
	// runners are busy, or GitHub has no scale set of that name in the runner
	// group.
	ScaleSetId    int64 `protobuf:"varint,3,opt,name=scale_set_id,json=scaleSetId,proto3" json:"scale_set_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScaleSetResponse) Reset() {
	*x = DeleteScaleSetResponse{}
	mi := &file_rungar_v1_rungar_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScaleSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScaleSetResponse) ProtoMessage() {}

func (x *DeleteScaleSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rungar_v1_rungar_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScaleSetResponse.ProtoReflect.Descriptor instead.
func (*DeleteScaleSetResponse) Descriptor() ([]byte, []int) {
	return file_rungar_v1_rungar_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteScaleSetResponse) GetRemoved() []*Runner {
	if x != nil {
		return x.Removed
	}
	return nil
}

func (x *DeleteScaleSetResponse) GetBusyLeft() int32 {
	if x != nil {
		return x.BusyLeft
	}
	return 0
}

func (x *DeleteScaleSetResponse) GetScaleSetId() int64 {
	if x != nil {
		return x.ScaleSetId
	}
	return 0
}

type PauseScaleSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseScaleSetRequest) Reset() {
	*x = PauseScaleSetRequest{}
	mi := &file_rungar_v1_rungar_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseScaleSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseScaleSetRequest) ProtoMessage() {}

func (x *PauseScaleSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rungar_v1_rungar_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseScaleSetRequest.ProtoReflect.Descriptor instead.
func (*PauseScaleSetRequest) Descriptor() ([]byte, []int) {
	return file_rungar_v1_rungar_proto_rawDescGZIP(), []int{14}
}

func (x *PauseScaleSetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ResumeScaleSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeScaleSetRequest) Reset() {
	*x = ResumeScaleSetRequest{}
	mi := &file_rungar_v1_rungar_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeScaleSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeScaleSetRequest) ProtoMessage() {}

func (x *ResumeScaleSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rungar_v1_rungar_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeScaleSetRequest.ProtoReflect.Descriptor instead.
func (*ResumeScaleSetRequest) Descriptor() ([]byte, []int) {
	return file_rungar_v1_rungar_proto_rawDescGZIP(), []int{15}
}

func (x *ResumeScaleSetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ReconcileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The scale sets to reconcile. Empty is every one.
	ScaleSets     []string `protobuf:"bytes,1,rep,name=scale_sets,json=scaleSets,proto3" json:"scale_sets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileRequest) Reset() {
	*x = ReconcileRequest{}
	mi := &file_rungar_v1_rungar_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileRequest) ProtoMessage() {}

func (x *ReconcileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rungar_v1_rungar_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileRequest.ProtoReflect.Descriptor instead.
func (*ReconcileRequest) Descriptor() ([]byte, []int) {
	return file_rungar_v1_rungar_proto_rawDescGZIP(), []int{16}
}

func (x *ReconcileRequest) GetScaleSets() []string {
	if x != nil {
		return x.ScaleSets
	}
	return nil
}

type ReconcileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The scale sets, as they are once reconciled.
	ScaleSets     []*ScaleSet `protobuf:"bytes,1,rep,name=scale_sets,json=scaleSets,proto3" json:"scale_sets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileResponse) Reset() {
	*x = ReconcileResponse{}
	mi := &file_rungar_v1_rungar_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileResponse) ProtoMessage() {}

func (x *ReconcileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rungar_v1_rungar_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileResponse.ProtoReflect.Descriptor instead.
func (*ReconcileResponse) Descriptor() ([]byte, []int) {
	return file_rungar_v1_rungar_proto_rawDescGZIP(), []int{17}
}

func (x *ReconcileResponse) GetScaleSets() []*ScaleSet {
	if x != nil {
		return x.ScaleSets
	}
	return nil
}

type ListProvidersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvidersRequest) Reset() {
	*x = ListProvidersRequest{}
	mi := &file_rungar_v1_rungar_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvidersRequest) ProtoMessage() {}

func (x *ListProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rungar_v1_rungar_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvidersRequest.ProtoReflect.Descriptor instead.
func (*ListProvidersRequest) Descriptor() ([]byte, []int) {
	return file_rungar_v1_rungar_proto_rawDescGZIP(), []int{18}
}

type ListProvidersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*Provider            `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvidersResponse) Reset() {
	*x = ListProvidersResponse{}
	mi := &file_rungar_v1_rungar_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvidersResponse) ProtoMessage() {}

func (x *ListProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rungar_v1_rungar_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvidersResponse.ProtoReflect.Descriptor instead.
func (*ListProvidersResponse) Descriptor() ([]byte, []int) {
	return file_rungar_v1_rungar_proto_rawDescGZIP(), []int{19}
}

func (x *ListProvidersResponse) GetProviders() []*Provider {
	if x != nil {
		return x.Providers
	}
	return nil
}

type GetProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderRequest) Reset() {
	*x = GetProviderRequest{}
	mi := &file_rungar_v1_rungar_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderRequest) ProtoMessage() {}

func (x *GetProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rungar_v1_rungar_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderRequest.ProtoReflect.Descriptor instead.
func (*GetProviderRequest) Descriptor() ([]byte, []int) {
	return file_rungar_v1_rungar_proto_rawDescGZIP(), []int{20}
}

func (x *GetProviderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DisableProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableProviderRequest) Reset() {
	*x = DisableProviderRequest{}
	mi := &file_rungar_v1_rungar_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableProviderRequest) ProtoMessage() {}

func (x *DisableProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rungar_v1_rungar_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableProviderRequest.ProtoReflect.Descriptor instead.
func (*DisableProviderRequest) Descriptor() ([]byte, []int) {
	return file_rungar_v1_rungar_proto_rawDescGZIP(), []int{21}
}

func (x *DisableProviderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EnableProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableProviderRequest) Reset() {
	*x = EnableProviderRequest{}
	mi := &file_rungar_v1_rungar_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableProviderRequest) ProtoMessage() {}

func (x *EnableProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rungar_v1_rungar_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableProviderRequest.ProtoReflect.Descriptor instead.
func (*EnableProviderRequest) Descriptor() ([]byte, []int) {
	return file_rungar_v1_rungar_proto_rawDescGZIP(), []int{22}
}

func (x *EnableProviderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Provider is one backend runners are placed on, as placement sees it now.
type Provider struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Its type: dicer.
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// What it is reached at.
	Endpoint string `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// Its placement weight, 1 unless configured.
	Weight float64 `protobuf:"fixed64,4,opt,name=weight,proto3" json:"weight,omitempty"`
	// Whether it is out of placement now.
	Disabled bool `protobuf:"varint,5,opt,name=disabled,proto3" json:"disabled,omitempty"`
	// Whether the configuration has it out of placement. Where this differs
	// from disabled, it was disabled or enabled while the daemon ran, and
	// goes back to this when the daemon restarts.
	ConfiguredDisabled bool `protobuf:"varint,6,opt,name=configured_disabled,json=configuredDisabled,proto3" json:"configured_disabled,omitempty"`
	// Whether it answered when last asked, and why not if it did not.
	Reachable bool   `protobuf:"varint,7,opt,name=reachable,proto3" json:"reachable,omitempty"`
	Error     string `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	// A scale set that found it full holding lower priorities back from it,
	// if one is.
	Hold *Hold `protobuf:"bytes,12,opt,name=hold,proto3" json:"hold,omitempty"`
	// This installation's runners on it.
	RunnerCount int32 `protobuf:"varint,13,opt,name=runner_count,json=runnerCount,proto3" json:"runner_count,omitempty"`
	// The most runners it may have, of every scale set, or 0 for no limit.
	MaxRunners int32 `protobuf:"varint,14,opt,name=max_runners,json=maxRunners,proto3" json:"max_runners,omitempty"`
	// The configured scale sets placed on it.
	ScaleSets []string `protobuf:"bytes,15,rep,name=scale_sets,json=scaleSets,proto3" json:"scale_sets,omitempty"`
	// How it stands for each scale set placed on it, in the order of
	// scale_sets.
	Placements    []*ProviderScaleSet `protobuf:"bytes,16,rep,name=placements,proto3" json:"placements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Provider) Reset() {
	*x = Provider{}
	mi := &file_rungar_v1_rungar_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provider) ProtoMessage() {}

func (x *Provider) ProtoReflect() protoreflect.Message {
	mi := &file_rungar_v1_rungar_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provider.ProtoReflect.Descriptor instead.
func (*Provider) Descriptor() ([]byte, []int) {
	return file_rungar_v1_rungar_proto_rawDescGZIP(), []int{23}
}

func (x *Provider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Provider) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Provider) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Provider) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Provider) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *Provider) GetConfiguredDisabled() bool {
	if x != nil {
		return x.ConfiguredDisabled
	}
	return false
}

func (x *Provider) GetReachable() bool {
	if x != nil {
		return x.Reachable
	}
	return false
}

func (x *Provider) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Provider) GetHold() *Hold {
	if x != nil {
		return x.Hold
	}
	return nil
}

func (x *Provider) GetRunnerCount() int32 {
	if x != nil {
		return x.RunnerCount
	}
	return 0
}

func (x *Provider) GetMaxRunners() int32 {
	if x != nil {
		return x.MaxRunners
	}
	return 0
}

func (x *Provider) GetScaleSets() []string {
	if x != nil {
		return x.ScaleSets
	}
	return nil
}

func (x *Provider) GetPlacements() []*ProviderScaleSet {
	if x != nil {
		return x.Placements
	}
	return nil
}

// ProviderScaleSet is how a provider stands for one scale set placed on it.
type ProviderScaleSet struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ScaleSet string                 `protobuf:"bytes,1,opt,name=scale_set,json=scaleSet,proto3" json:"scale_set,omitempty"`
	// How long the scale set will keep skipping the provider after it
	// refused the scale set's runner. Absent when it tries it.
	BackoffFor *durationpb.Duration `protobuf:"bytes,4,opt,name=backoff_for,json=backoffFor,proto3" json:"backoff_for,omitempty"`
	// How many times in a row the provider refused, and why it last did.
	Failures int32  `protobuf:"varint,5,opt,name=failures,proto3" json:"failures,omitempty"`
	Failure  string `protobuf:"bytes,6,opt,name=failure,proto3" json:"failure,omitempty"`
	// Whether the last refusal said the provider was full.
	Full          bool `protobuf:"varint,7,opt,name=full,proto3" json:"full,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderScaleSet) Reset() {
	*x = ProviderScaleSet{}
	mi := &file_rungar_v1_rungar_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderScaleSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderScaleSet) ProtoMessage() {}

func (x *ProviderScaleSet) ProtoReflect() protoreflect.Message {
	mi := &file_rungar_v1_rungar_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderScaleSet.ProtoReflect.Descriptor instead.
func (*ProviderScaleSet) Descriptor() ([]byte, []int) {
	return file_rungar_v1_rungar_proto_rawDescGZIP(), []int{24}
}

func (x *ProviderScaleSet) GetScaleSet() string {
	if x != nil {
		return x.ScaleSet
	}
	return ""
}

func (x *ProviderScaleSet) GetBackoffFor() *durationpb.Duration {
	if x != nil {
		return x.BackoffFor
	}
	return nil
}

func (x *ProviderScaleSet) GetFailures() int32 {
	if x != nil {
		return x.Failures
	}
	return 0
}

func (x *ProviderScaleSet) GetFailure() string {
	if x != nil {
		return x.Failure
	}
	return ""
}

func (x *ProviderScaleSet) GetFull() bool {
	if x != nil {
		return x.Full
	}
	return false
}

// Hold is a scale set keeping lower priorities off a provider until it finds
// room.
type Hold struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ScaleSet string                 `protobuf:"bytes,1,opt,name=scale_set,json=scaleSet,proto3" json:"scale_set,omitempty"`
	Priority int32                  `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	// How long it lasts unless renewed.
	Remaining     *durationpb.Duration `protobuf:"bytes,3,opt,name=remaining,proto3" json:"remaining,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hold) Reset() {
	*x = Hold{}
	mi := &file_rungar_v1_rungar_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hold) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hold) ProtoMessage() {}

func (x *Hold) ProtoReflect() protoreflect.Message {
	mi := &file_rungar_v1_rungar_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hold.ProtoReflect.Descriptor instead.
func (*Hold) Descriptor() ([]byte, []int) {
	return file_rungar_v1_rungar_proto_rawDescGZIP(), []int{25}
}

func (x *Hold) GetScaleSet() string {
	if x != nil {
		return x.ScaleSet
	}
	return ""
}

func (x *Hold) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Hold) GetRemaining() *durationpb.Duration {
	if x != nil {
		return x.Remaining
	}
	return nil
}

type ListRunnersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Only this scale set's runners.
	ScaleSet string `protobuf:"bytes,1,opt,name=scale_set,json=scaleSet,proto3" json:"scale_set,omitempty"`
	// Only the runners on this provider.
	Provider      string `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunnersRequest) Reset() {
	*x = ListRunnersRequest{}
	mi := &file_rungar_v1_rungar_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunnersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunnersRequest) ProtoMessage() {}

func (x *ListRunnersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rungar_v1_rungar_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunnersRequest.ProtoReflect.Descriptor instead.
func (*ListRunnersRequest) Descriptor() ([]byte, []int) {
	return file_rungar_v1_rungar_proto_rawDescGZIP(), []int{26}
}

func (x *ListRunnersRequest) GetScaleSet() string {
	if x != nil {
		return x.ScaleSet
	}
	return ""
}

func (x *ListRunnersRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type ListRunnersResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Runners []*Runner              `protobuf:"bytes,1,rep,name=runners,proto3" json:"runners,omitempty"`
	// Providers that could not be listed, by name, with why.
	UnreachableProviders map[string]string `protobuf:"bytes,2,rep,name=unreachable_providers,json=unreachableProviders,proto3" json:"unreachable_providers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Why GitHub could not be asked what the runners are doing, if it could
	// not.
	GithubError   string `protobuf:"bytes,3,opt,name=github_error,json=githubError,proto3" json:"github_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunnersResponse) Reset() {
	*x = ListRunnersResponse{}
	mi := &file_rungar_v1_rungar_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunnersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunnersResponse) ProtoMessage() {}

func (x *ListRunnersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rungar_v1_rungar_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunnersResponse.ProtoReflect.Descriptor instead.
func (*ListRunnersResponse) Descriptor() ([]byte, []int) {
	return file_rungar_v1_rungar_proto_rawDescGZIP(), []int{27}
}

func (x *ListRunnersResponse) GetRunners() []*Runner {
	if x != nil {
		return x.Runners
	}
	return nil
}

func (x *ListRunnersResponse) GetUnreachableProviders() map[string]string {
	if x != nil {
		return x.UnreachableProviders
	}
	return nil
}

func (x *ListRunnersResponse) GetGithubError() string {
	if x != nil {
		return x.GithubError
	}
	return ""
}

type DeleteRunnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRunnerRequest) Reset() {
	*x = DeleteRunnerRequest{}
	mi := &file_rungar_v1_rungar_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRunnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRunnerRequest) ProtoMessage() {}

func (x *DeleteRunnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rungar_v1_rungar_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRunnerRequest.ProtoReflect.Descriptor instead.
func (*DeleteRunnerRequest) Descriptor() ([]byte, []int) {
	return file_rungar_v1_rungar_proto_rawDescGZIP(), []int{28}
}

func (x *DeleteRunnerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Runner is one runner: its machine, what the daemon knows of it, and what
// GitHub says it is doing.
type Runner struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Name     string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ScaleSet string                 `protobuf:"bytes,2,opt,name=scale_set,json=scaleSet,proto3" json:"scale_set,omitempty"`
	Provider string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	// What the daemon knows it to be doing. Unspecified for a runner of a
	// scale set it does not run.
	State RunnerState `protobuf:"varint,4,opt,name=state,proto3,enum=rungar.v1.RunnerState" json:"state,omitempty"`
	// The machine's state, as its provider says it: running, stopped.
	MachineState string `protobuf:"bytes,5,opt,name=machine_state,json=machineState,proto3" json:"machine_state,omitempty"`
	// What GitHub says it is doing. Unspecified when GitHub was not asked.
	GithubStatus RunnerGitHubStatus `protobuf:"varint,6,opt,name=github_status,json=githubStatus,proto3,enum=rungar.v1.RunnerGitHubStatus" json:"github_status,omitempty"`
	// The job it is running, when the daemon knows it is busy.
	JobId         string                 `protobuf:"bytes,7,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Runner) Reset() {
	*x = Runner{}
	mi := &file_rungar_v1_rungar_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Runner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Runner) ProtoMessage() {}

func (x *Runner) ProtoReflect() protoreflect.Message {
	mi := &file_rungar_v1_rungar_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Runner.ProtoReflect.Descriptor instead.
func (*Runner) Descriptor() ([]byte, []int) {
	return file_rungar_v1_rungar_proto_rawDescGZIP(), []int{29}
}

func (x *Runner) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Runner) GetScaleSet() string {
	if x != nil {
		return x.ScaleSet
	}
	return ""
}

func (x *Runner) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Runner) GetState() RunnerState {
	if x != nil {
		return x.State
	}
	return RunnerState_RUNNER_STATE_UNSPECIFIED
}

func (x *Runner) GetMachineState() string {
	if x != nil {
		return x.MachineState
	}
	return ""
}

func (x *Runner) GetGithubStatus() RunnerGitHubStatus {
	if x != nil {
		return x.GithubStatus
	}
	return RunnerGitHubStatus_RUNNER_GIT_HUB_STATUS_UNSPECIFIED
}

func (x *Runner) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Runner) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

// ListEventsRequest picks events: every one, unless narrowed.
type ListEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Only the events of this scale set.
	ScaleSet string `protobuf:"bytes,1,opt,name=scale_set,json=scaleSet,proto3" json:"scale_set,omitempty"`
	// Only the events on this provider: of its runners, and of it.
	Provider string `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	// Only the events of the runner of this name.
	Runner string `protobuf:"bytes,3,opt,name=runner,proto3" json:"runner,omitempty"`
	// Only the events since this time.
	Since *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=since,proto3" json:"since,omitempty"`
	// Only the last this many of the history. 0 is all of it.
	Limit int32 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	// Keep the stream open, sending each new event as it happens.
	Follow        bool `protobuf:"varint,6,opt,name=follow,proto3" json:"follow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_rungar_v1_rungar_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rungar_v1_rungar_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_rungar_v1_rungar_proto_rawDescGZIP(), []int{30}
}

func (x *ListEventsRequest) GetScaleSet() string {
	if x != nil {
		return x.ScaleSet
	}
	return ""
}

func (x *ListEventsRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ListEventsRequest) GetRunner() string {
	if x != nil {
		return x.Runner
	}
	return ""
}

func (x *ListEventsRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *ListEventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListEventsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

type ListEventsResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Events []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	// Set on the last batch of the history, after which, with follow, each
	// response is a new event.
	CaughtUp      bool `protobuf:"varint,2,opt,name=caught_up,json=caughtUp,proto3" json:"caught_up,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_rungar_v1_rungar_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rungar_v1_rungar_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_rungar_v1_rungar_proto_rawDescGZIP(), []int{31}
}

func (x *ListEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ListEventsResponse) GetCaughtUp() bool {
	if x != nil {
		return x.CaughtUp
	}
	return false
}

// Event is one thing the daemon did, or found, to one runner, provider or
// scale set.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Time  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Kind  EventKind              `protobuf:"varint,2,opt,name=kind,proto3,enum=rungar.v1.EventKind" json:"kind,omitempty"`
	// The runner's, the provider's or the scale set's.
	Name   string      `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Action EventAction `protobuf:"varint,4,opt,name=action,proto3,enum=rungar.v1.EventAction" json:"action,omitempty"`
	// The scale set it happened for.
	ScaleSet string `protobuf:"bytes,5,opt,name=scale_set,json=scaleSet,proto3" json:"scale_set,omitempty"`
	// The provider it happened on: a runner's, or the provider itself.
	Provider string `protobuf:"bytes,6,opt,name=provider,proto3" json:"provider,omitempty"`
	// What happened, in a line, for a person.
	Message string `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	// What happened, for a program. A runner removed or lost has its reason;
	// a provider found full or failing has the runner it refused, the error,
	// how long the scale set skips it for, and, failing, its failures in a
	// row.
	Attributes    map[string]string `protobuf:"bytes,8,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_rungar_v1_rungar_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_rungar_v1_rungar_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_rungar_v1_rungar_proto_rawDescGZIP(), []int{32}
}

func (x *Event) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Event) GetKind() EventKind {
	if x != nil {
		return x.Kind
	}
	return EventKind_EVENT_KIND_UNSPECIFIED
}

func (x *Event) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Event) GetAction() EventAction {
	if x != nil {
		return x.Action
	}
	return EventAction_EVENT_ACTION_UNSPECIFIED
}

func (x *Event) GetScaleSet() string {
	if x != nil {
		return x.ScaleSet
	}
	return ""
}

func (x *Event) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Event) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Event) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

var File_rungar_v1_rungar_proto protoreflect.FileDescriptor

const file_rungar_v1_rungar_proto_rawDesc = "" +
	"\n" +
	"\x16rungar/v1/rungar.proto\x12\trungar.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x12\n" +
	"\x10GetStatusRequest\"\x92\x03\n" +
	"\fDaemonStatus\x12)\n" +
	"\x06daemon\x18\x01 \x01(\v2\x11.rungar.v1.DaemonR\x06daemon\x122\n" +
	"\n" +
	"scale_sets\x18\x02 \x03(\v2\x13.rungar.v1.ScaleSetR\tscaleSets\x121\n" +
	"\tproviders\x18\x03 \x03(\v2\x13.rungar.v1.ProviderR\tproviders\x12+\n" +
	"\arunners\x18\x04 \x03(\v2\x11.rungar.v1.RunnerR\arunners\x12f\n" +
	"\x15unreachable_providers\x18\x05 \x03(\v21.rungar.v1.DaemonStatus.UnreachableProvidersEntryR\x14unreachableProviders\x1aG\n" +
	"\x19UnreachableProvidersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x06\x10\aR\fgithub_error\"\xe5\x01\n" +
	"\x06Daemon\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06commit\x18\x02 \x01(\tR\x06commit\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12\x1f\n" +
	"\vconfig_file\x18\x05 \x01(\tR\n" +
	"configFile\x12\"\n" +
	"\finstallation\x18\x06 \x01(\tR\finstallation\x12)\n" +
	"\x06github\x18\a \x01(\v2\x11.rungar.v1.GitHubR\x06github\"\x7f\n" +
	"\x06GitHub\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\x12 \n" +
	"\vcredentials\x18\x03 \x01(\tR\vcredentials\x12+\n" +
	"\x11credentials_error\x18\x04 \x01(\tR\x10credentialsError\"\x16\n" +
	"\x14ListScaleSetsRequest\"\x85\x02\n" +
	"\x15ListScaleSetsResponse\x122\n" +
	"\n" +
	"scale_sets\x18\x01 \x03(\v2\x13.rungar.v1.ScaleSetR\tscaleSets\x12o\n" +
	"\x15unreachable_providers\x18\x02 \x03(\v2:.rungar.v1.ListScaleSetsResponse.UnreachableProvidersEntryR\x14unreachableProviders\x1aG\n" +
	"\x19UnreachableProvidersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"K\n" +
	"\x12GetScaleSetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\frunner_group\x18\x02 \x01(\tR\vrunnerGroup\"\xca\x05\n" +
	"\bScaleSet\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"configured\x18\x02 \x01(\bR\n" +
	"configured\x12\x16\n" +
	"\x06labels\x18\x03 \x03(\tR\x06labels\x12\x1c\n" +
	"\tproviders\x18\x04 \x03(\tR\tproviders\x12\x1c\n" +
	"\tplacement\x18\x05 \x01(\tR\tplacement\x128\n" +
	"\frunner_sizes\x18\x06 \x03(\v2\x15.rungar.v1.RunnerSizeR\vrunnerSizes\x12\x1f\n" +
	"\vmin_runners\x18\a \x01(\x05R\n" +
	"minRunners\x12\x1f\n" +
	"\vmax_runners\x18\b \x01(\x05R\n" +
	"maxRunners\x12\x1a\n" +
	"\bpriority\x18\t \x01(\x05R\bpriority\x12!\n" +
	"\frunner_group\x18\n" +
	" \x01(\tR\vrunnerGroup\x12\x17\n" +
	"\aruns_on\x18\v \x01(\tR\x06runsOn\x12.\n" +
	"\x05phase\x18\f \x01(\x0e2\x18.rungar.v1.ScaleSetPhaseR\x05phase\x12'\n" +
	"\x0fdesired_runners\x18\r \x01(\x05R\x0edesiredRunners\x12<\n" +
	"\rrunner_counts\x18\x0e \x01(\v2\x17.rungar.v1.RunnerCountsR\frunnerCounts\x12.\n" +
	"\x13holding_back_reason\x18\x0f \x01(\tR\x11holdingBackReason\x12#\n" +
	"\rfleet_runners\x18\x10 \x01(\x05R\ffleetRunners\x121\n" +
	"\x06github\x18\x11 \x01(\v2\x19.rungar.v1.GitHubScaleSetR\x06github\x12\x16\n" +
	"\x06paused\x18\x12 \x01(\bR\x06paused\x12+\n" +
	"\x11configured_paused\x18\x13 \x01(\bR\x10configuredPaused\"J\n" +
	"\n" +
	"RunnerSize\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"R\n" +
	"\fRunnerCounts\x12\x1a\n" +
	"\bstarting\x18\x01 \x01(\x05R\bstarting\x12\x12\n" +
	"\x04idle\x18\x02 \x01(\x05R\x04idle\x12\x12\n" +
	"\x04busy\x18\x03 \x01(\x05R\x04busy\"\x83\x02\n" +
	"\x0eGitHubScaleSet\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\x12!\n" +
	"\frunner_group\x18\x04 \x01(\tR\vrunnerGroup\x12\x16\n" +
	"\x06labels\x18\x05 \x03(\tR\x06labels\x12;\n" +
	"\vcreate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12=\n" +
	"\n" +
	"statistics\x18\a \x01(\v2\x1d.rungar.v1.ScaleSetStatisticsR\n" +
	"statistics\"\xd1\x01\n" +
	"\x12ScaleSetStatistics\x12#\n" +
	"\rassigned_jobs\x18\x01 \x01(\x05R\fassignedJobs\x12!\n" +
	"\frunning_jobs\x18\x02 \x01(\x05R\vrunningJobs\x12-\n" +
	"\x12registered_runners\x18\x03 \x01(\x05R\x11registeredRunners\x12!\n" +
	"\fbusy_runners\x18\x04 \x01(\x05R\vbusyRunners\x12!\n" +
	"\fidle_runners\x18\x05 \x01(\x05R\vidleRunners\"N\n" +
	"\x15DeleteScaleSetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\frunner_group\x18\x02 \x01(\tR\vrunnerGroup\"\x84\x01\n" +
	"\x16DeleteScaleSetResponse\x12+\n" +
	"\aremoved\x18\x01 \x03(\v2\x11.rungar.v1.RunnerR\aremoved\x12\x1b\n" +
	"\tbusy_left\x18\x02 \x01(\x05R\bbusyLeft\x12 \n" +
	"\fscale_set_id\x18\x03 \x01(\x03R\n" +
	"scaleSetId\"*\n" +
	"\x14PauseScaleSetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"+\n" +
	"\x15ResumeScaleSetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"1\n" +
	"\x10ReconcileRequest\x12\x1d\n" +
	"\n" +
	"scale_sets\x18\x01 \x03(\tR\tscaleSets\"G\n" +
	"\x11ReconcileResponse\x122\n" +
	"\n" +
	"scale_sets\x18\x01 \x03(\v2\x13.rungar.v1.ScaleSetR\tscaleSets\"\x16\n" +
	"\x14ListProvidersRequest\"J\n" +
	"\x15ListProvidersResponse\x121\n" +
	"\tproviders\x18\x01 \x03(\v2\x13.rungar.v1.ProviderR\tproviders\"(\n" +
	"\x12GetProviderRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\",\n" +
	"\x16DisableProviderRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"+\n" +
	"\x15EnableProviderRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xe2\x03\n" +
	"\bProvider\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x01R\x06weight\x12\x1a\n" +
	"\bdisabled\x18\x05 \x01(\bR\bdisabled\x12/\n" +
	"\x13configured_disabled\x18\x06 \x01(\bR\x12configuredDisabled\x12\x1c\n" +
	"\treachable\x18\a \x01(\bR\treachable\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x12#\n" +
	"\x04hold\x18\f \x01(\v2\x0f.rungar.v1.HoldR\x04hold\x12!\n" +
	"\frunner_count\x18\r \x01(\x05R\vrunnerCount\x12\x1f\n" +
	"\vmax_runners\x18\x0e \x01(\x05R\n" +
	"maxRunners\x12\x1d\n" +
	"\n" +
	"scale_sets\x18\x0f \x03(\tR\tscaleSets\x12;\n" +
	"\n" +
	"placements\x18\x10 \x03(\v2\x1b.rungar.v1.ProviderScaleSetR\n" +
	"placementsJ\x04\b\t\x10\n" +
	"J\x04\b\n" +
	"\x10\vJ\x04\b\v\x10\fR\x0fpassed_over_forR\bfailuresR\arefusal\"\xd4\x01\n" +
	"\x10ProviderScaleSet\x12\x1b\n" +
	"\tscale_set\x18\x01 \x01(\tR\bscaleSet\x12:\n" +
	"\vbackoff_for\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\n" +
	"backoffFor\x12\x1a\n" +
	"\bfailures\x18\x05 \x01(\x05R\bfailures\x12\x18\n" +
	"\afailure\x18\x06 \x01(\tR\afailure\x12\x12\n" +
	"\x04full\x18\a \x01(\bR\x04fullJ\x04\b\x02\x10\x03J\x04\b\x03\x10\x04R\bfull_forR\arefused\"x\n" +
	"\x04Hold\x12\x1b\n" +
	"\tscale_set\x18\x01 \x01(\tR\bscaleSet\x12\x1a\n" +
	"\bpriority\x18\x02 \x01(\x05R\bpriority\x127\n" +
	"\tremaining\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\tremaining\"M\n" +
	"\x12ListRunnersRequest\x12\x1b\n" +
	"\tscale_set\x18\x01 \x01(\tR\bscaleSet\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\"\x9d\x02\n" +
	"\x13ListRunnersResponse\x12+\n" +
	"\arunners\x18\x01 \x03(\v2\x11.rungar.v1.RunnerR\arunners\x12m\n" +
	"\x15unreachable_providers\x18\x02 \x03(\v28.rungar.v1.ListRunnersResponse.UnreachableProvidersEntryR\x14unreachableProviders\x12!\n" +
	"\fgithub_error\x18\x03 \x01(\tR\vgithubError\x1aG\n" +
	"\x19UnreachableProvidersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\")\n" +
	"\x13DeleteRunnerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xc0\x02\n" +
	"\x06Runner\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tscale_set\x18\x02 \x01(\tR\bscaleSet\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12,\n" +
	"\x05state\x18\x04 \x01(\x0e2\x16.rungar.v1.RunnerStateR\x05state\x12#\n" +
	"\rmachine_state\x18\x05 \x01(\tR\fmachineState\x12B\n" +
	"\rgithub_status\x18\x06 \x01(\x0e2\x1d.rungar.v1.RunnerGitHubStatusR\fgithubStatus\x12\x15\n" +
	"\x06job_id\x18\a \x01(\tR\x05jobId\x12;\n" +
	"\vcreate_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\"\xc4\x01\n" +
	"\x11ListEventsRequest\x12\x1b\n" +
	"\tscale_set\x18\x01 \x01(\tR\bscaleSet\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x16\n" +
	"\x06runner\x18\x03 \x01(\tR\x06runner\x120\n" +
	"\x05since\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06follow\x18\x06 \x01(\bR\x06follow\"[\n" +
	"\x12ListEventsResponse\x12(\n" +
	"\x06events\x18\x01 \x03(\v2\x10.rungar.v1.EventR\x06events\x12\x1b\n" +
	"\tcaught_up\x18\x02 \x01(\bR\bcaughtUp\"\xf9\x02\n" +
	"\x05Event\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12(\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x14.rungar.v1.EventKindR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12.\n" +
	"\x06action\x18\x04 \x01(\x0e2\x16.rungar.v1.EventActionR\x06action\x12\x1b\n" +
	"\tscale_set\x18\x05 \x01(\tR\bscaleSet\x12\x1a\n" +
	"\bprovider\x18\x06 \x01(\tR\bprovider\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x12@\n" +
	"\n" +
	"attributes\x18\b \x03(\v2 .rungar.v1.Event.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\x96\x01\n" +
	"\rScaleSetPhase\x12\x1f\n" +
	"\x1bSCALE_SET_PHASE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18SCALE_SET_PHASE_STARTING\x10\x01\x12'\n" +
	"#SCALE_SET_PHASE_WAITING_FOR_SESSION\x10\x02\x12\x1d\n" +
	"\x19SCALE_SET_PHASE_LISTENING\x10\x03*t\n" +
	"\vRunnerState\x12\x1c\n" +
	"\x18RUNNER_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15RUNNER_STATE_STARTING\x10\x01\x12\x15\n" +
	"\x11RUNNER_STATE_IDLE\x10\x02\x12\x15\n" +
	"\x11RUNNER_STATE_BUSY\x10\x03*\xc8\x01\n" +
	"\x12RunnerGitHubStatus\x12%\n" +
	"!RUNNER_GIT_HUB_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aRUNNER_GIT_HUB_STATUS_BUSY\x10\x01\x12\x1e\n" +
	"\x1aRUNNER_GIT_HUB_STATUS_IDLE\x10\x02\x12!\n" +
	"\x1dRUNNER_GIT_HUB_STATUS_OFFLINE\x10\x03\x12(\n" +
	"$RUNNER_GIT_HUB_STATUS_NOT_REGISTERED\x10\x04*q\n" +
	"\tEventKind\x12\x1a\n" +
	"\x16EVENT_KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11EVENT_KIND_RUNNER\x10\x01\x12\x17\n" +
	"\x13EVENT_KIND_PROVIDER\x10\x02\x12\x18\n" +
	"\x14EVENT_KIND_SCALE_SET\x10\x03*\xb4\x02\n" +
	"\vEventAction\x12\x1c\n" +
	"\x18EVENT_ACTION_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14EVENT_ACTION_CREATED\x10\x01\x12\x18\n" +
	"\x14EVENT_ACTION_ADOPTED\x10\x02\x12\x18\n" +
	"\x14EVENT_ACTION_REMOVED\x10\x03\x12\x15\n" +
	"\x11EVENT_ACTION_LOST\x10\x04\x12\x15\n" +
	"\x11EVENT_ACTION_FULL\x10\x06\x12\x18\n" +
	"\x14EVENT_ACTION_FAILING\x10\b\x12\x17\n" +
	"\x13EVENT_ACTION_PAUSED\x10\t\x12\x18\n" +
	"\x14EVENT_ACTION_RESUMED\x10\n" +
	"\"\x04\b\x05\x10\x05\"\x04\b\a\x10\a*\x18EVENT_ACTION_PASSED_OVER*\x18EVENT_ACTION_CANNOT_MAKE2\xa1\b\n" +
	"\rRungarService\x12A\n" +
	"\tGetStatus\x12\x1b.rungar.v1.GetStatusRequest\x1a\x17.rungar.v1.DaemonStatus\x12R\n" +
	"\rListScaleSets\x12\x1f.rungar.v1.ListScaleSetsRequest\x1a .rungar.v1.ListScaleSetsResponse\x12A\n" +
	"\vGetScaleSet\x12\x1d.rungar.v1.GetScaleSetRequest\x1a\x13.rungar.v1.ScaleSet\x12U\n" +
	"\x0eDeleteScaleSet\x12 .rungar.v1.DeleteScaleSetRequest\x1a!.rungar.v1.DeleteScaleSetResponse\x12F\n" +
	"\tReconcile\x12\x1b.rungar.v1.ReconcileRequest\x1a\x1c.rungar.v1.ReconcileResponse\x12E\n" +
	"\rPauseScaleSet\x12\x1f.rungar.v1.PauseScaleSetRequest\x1a\x13.rungar.v1.ScaleSet\x12G\n" +
	"\x0eResumeScaleSet\x12 .rungar.v1.ResumeScaleSetRequest\x1a\x13.rungar.v1.ScaleSet\x12R\n" +
	"\rListProviders\x12\x1f.rungar.v1.ListProvidersRequest\x1a .rungar.v1.ListProvidersResponse\x12A\n" +
	"\vGetProvider\x12\x1d.rungar.v1.GetProviderRequest\x1a\x13.rungar.v1.Provider\x12I\n" +
	"\x0fDisableProvider\x12!.rungar.v1.DisableProviderRequest\x1a\x13.rungar.v1.Provider\x12G\n" +
	"\x0eEnableProvider\x12 .rungar.v1.EnableProviderRequest\x1a\x13.rungar.v1.Provider\x12L\n" +
	"\vListRunners\x12\x1d.rungar.v1.ListRunnersRequest\x1a\x1e.rungar.v1.ListRunnersResponse\x12A\n" +
	"\fDeleteRunner\x12\x1e.rungar.v1.DeleteRunnerRequest\x1a\x11.rungar.v1.Runner\x12K\n" +
	"\n" +
	"ListEvents\x12\x1c.rungar.v1.ListEventsRequest\x1a\x1d.rungar.v1.ListEventsResponse0\x01B6Z4github.com/konradasb/rungar/proto/rungar/v1;rungarv1b\x06proto3"

var (
	file_rungar_v1_rungar_proto_rawDescOnce sync.Once
	file_rungar_v1_rungar_proto_rawDescData []byte
)

func file_rungar_v1_rungar_proto_rawDescGZIP() []byte {
	file_rungar_v1_rungar_proto_rawDescOnce.Do(func() {
		file_rungar_v1_rungar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rungar_v1_rungar_proto_rawDesc), len(file_rungar_v1_rungar_proto_rawDesc)))
	})
	return file_rungar_v1_rungar_proto_rawDescData
}

var file_rungar_v1_rungar_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_rungar_v1_rungar_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_rungar_v1_rungar_proto_goTypes = []any{
	(ScaleSetPhase)(0),             // 0: rungar.v1.ScaleSetPhase
	(RunnerState)(0),               // 1: rungar.v1.RunnerState
	(RunnerGitHubStatus)(0),        // 2: rungar.v1.RunnerGitHubStatus
	(EventKind)(0),                 // 3: rungar.v1.EventKind
	(EventAction)(0),               // 4: rungar.v1.EventAction
	(*GetStatusRequest)(nil),       // 5: rungar.v1.GetStatusRequest
	(*DaemonStatus)(nil),           // 6: rungar.v1.DaemonStatus
	(*Daemon)(nil),                 // 7: rungar.v1.Daemon
	(*GitHub)(nil),                 // 8: rungar.v1.GitHub
	(*ListScaleSetsRequest)(nil),   // 9: rungar.v1.ListScaleSetsRequest
	(*ListScaleSetsResponse)(nil),  // 10: rungar.v1.ListScaleSetsResponse
	(*GetScaleSetRequest)(nil),     // 11: rungar.v1.GetScaleSetRequest
	(*ScaleSet)(nil),               // 12: rungar.v1.ScaleSet
	(*RunnerSize)(nil),             // 13: rungar.v1.RunnerSize
	(*RunnerCounts)(nil),           // 14: rungar.v1.RunnerCounts
	(*GitHubScaleSet)(nil),         // 15: rungar.v1.GitHubScaleSet
	(*ScaleSetStatistics)(nil),     // 16: rungar.v1.ScaleSetStatistics
	(*DeleteScaleSetRequest)(nil),  // 17: rungar.v1.DeleteScaleSetRequest
	(*DeleteScaleSetResponse)(nil), // 18: rungar.v1.DeleteScaleSetResponse
	(*PauseScaleSetRequest)(nil),   // 19: rungar.v1.PauseScaleSetRequest
	(*ResumeScaleSetRequest)(nil),  // 20: rungar.v1.ResumeScaleSetRequest
	(*ReconcileRequest)(nil),       // 21: rungar.v1.ReconcileRequest
	(*ReconcileResponse)(nil),      // 22: rungar.v1.ReconcileResponse
	(*ListProvidersRequest)(nil),   // 23: rungar.v1.ListProvidersRequest
	(*ListProvidersResponse)(nil),  // 24: rungar.v1.ListProvidersResponse
	(*GetProviderRequest)(nil),     // 25: rungar.v1.GetProviderRequest
	(*DisableProviderRequest)(nil), // 26: rungar.v1.DisableProviderRequest
	(*EnableProviderRequest)(nil),  // 27: rungar.v1.EnableProviderRequest
	(*Provider)(nil),               // 28: rungar.v1.Provider
	(*ProviderScaleSet)(nil),       // 29: rungar.v1.ProviderScaleSet
	(*Hold)(nil),                   // 30: rungar.v1.Hold
	(*ListRunnersRequest)(nil),     // 31: rungar.v1.ListRunnersRequest
	(*ListRunnersResponse)(nil),    // 32: rungar.v1.ListRunnersResponse
	(*DeleteRunnerRequest)(nil),    // 33: rungar.v1.DeleteRunnerRequest
	(*Runner)(nil),                 // 34: rungar.v1.Runner
	(*ListEventsRequest)(nil),      // 35: rungar.v1.ListEventsRequest
	(*ListEventsResponse)(nil),     // 36: rungar.v1.ListEventsResponse
	(*Event)(nil),                  // 37: rungar.v1.Event
	nil,                            // 38: rungar.v1.DaemonStatus.UnreachableProvidersEntry
	nil,                            // 39: rungar.v1.ListScaleSetsResponse.UnreachableProvidersEntry
	nil,                            // 40: rungar.v1.ListRunnersResponse.UnreachableProvidersEntry
	nil,                            // 41: rungar.v1.Event.AttributesEntry
	(*timestamppb.Timestamp)(nil),  // 42: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),    // 43: google.protobuf.Duration
}
var file_rungar_v1_rungar_proto_depIdxs = []int32{
	7,  // 0: rungar.v1.DaemonStatus.daemon:type_name -> rungar.v1.Daemon
	12, // 1: rungar.v1.DaemonStatus.scale_sets:type_name -> rungar.v1.ScaleSet
	28, // 2: rungar.v1.DaemonStatus.providers:type_name -> rungar.v1.Provider
	34, // 3: rungar.v1.DaemonStatus.runners:type_name -> rungar.v1.Runner
	38, // 4: rungar.v1.DaemonStatus.unreachable_providers:type_name -> rungar.v1.DaemonStatus.UnreachableProvidersEntry
	42, // 5: rungar.v1.Daemon.start_time:type_name -> google.protobuf.Timestamp
	8,  // 6: rungar.v1.Daemon.github:type_name -> rungar.v1.GitHub
	12, // 7: rungar.v1.ListScaleSetsResponse.scale_sets:type_name -> rungar.v1.ScaleSet
	39, // 8: rungar.v1.ListScaleSetsResponse.unreachable_providers:type_name -> rungar.v1.ListScaleSetsResponse.UnreachableProvidersEntry
	13, // 9: rungar.v1.ScaleSet.runner_sizes:type_name -> rungar.v1.RunnerSize
	0,  // 10: rungar.v1.ScaleSet.phase:type_name -> rungar.v1.ScaleSetPhase
	14, // 11: rungar.v1.ScaleSet.runner_counts:type_name -> rungar.v1.RunnerCounts
	15, // 12: rungar.v1.ScaleSet.github:type_name -> rungar.v1.GitHubScaleSet
	42, // 13: rungar.v1.GitHubScaleSet.create_time:type_name -> google.protobuf.Timestamp
	16, // 14: rungar.v1.GitHubScaleSet.statistics:type_name -> rungar.v1.ScaleSetStatistics
	34, // 15: rungar.v1.DeleteScaleSetResponse.removed:type_name -> rungar.v1.Runner
	12, // 16: rungar.v1.ReconcileResponse.scale_sets:type_name -> rungar.v1.ScaleSet
	28, // 17: rungar.v1.ListProvidersResponse.providers:type_name -> rungar.v1.Provider
	30, // 18: rungar.v1.Provider.hold:type_name -> rungar.v1.Hold
	29, // 19: rungar.v1.Provider.placements:type_name -> rungar.v1.ProviderScaleSet
	43, // 20: rungar.v1.ProviderScaleSet.backoff_for:type_name -> google.protobuf.Duration
	43, // 21: rungar.v1.Hold.remaining:type_name -> google.protobuf.Duration
	34, // 22: rungar.v1.ListRunnersResponse.runners:type_name -> rungar.v1.Runner
	40, // 23: rungar.v1.ListRunnersResponse.unreachable_providers:type_name -> rungar.v1.ListRunnersResponse.UnreachableProvidersEntry
	1,  // 24: rungar.v1.Runner.state:type_name -> rungar.v1.RunnerState
	2,  // 25: rungar.v1.Runner.github_status:type_name -> rungar.v1.RunnerGitHubStatus
	42, // 26: rungar.v1.Runner.create_time:type_name -> google.protobuf.Timestamp
	42, // 27: rungar.v1.ListEventsRequest.since:type_name -> google.protobuf.Timestamp
	37, // 28: rungar.v1.ListEventsResponse.events:type_name -> rungar.v1.Event
	42, // 29: rungar.v1.Event.time:type_name -> google.protobuf.Timestamp
	3,  // 30: rungar.v1.Event.kind:type_name -> rungar.v1.EventKind
	4,  // 31: rungar.v1.Event.action:type_name -> rungar.v1.EventAction
	41, // 32: rungar.v1.Event.attributes:type_name -> rungar.v1.Event.AttributesEntry
	5,  // 33: rungar.v1.RungarService.GetStatus:input_type -> rungar.v1.GetStatusRequest
	9,  // 34: rungar.v1.RungarService.ListScaleSets:input_type -> rungar.v1.ListScaleSetsRequest
	11, // 35: rungar.v1.RungarService.GetScaleSet:input_type -> rungar.v1.GetScaleSetRequest
	17, // 36: rungar.v1.RungarService.DeleteScaleSet:input_type -> rungar.v1.DeleteScaleSetRequest
	21, // 37: rungar.v1.RungarService.Reconcile:input_type -> rungar.v1.ReconcileRequest
	19, // 38: rungar.v1.RungarService.PauseScaleSet:input_type -> rungar.v1.PauseScaleSetRequest
	20, // 39: rungar.v1.RungarService.ResumeScaleSet:input_type -> rungar.v1.ResumeScaleSetRequest
	23, // 40: rungar.v1.RungarService.ListProviders:input_type -> rungar.v1.ListProvidersRequest
	25, // 41: rungar.v1.RungarService.GetProvider:input_type -> rungar.v1.GetProviderRequest
	26, // 42: rungar.v1.RungarService.DisableProvider:input_type -> rungar.v1.DisableProviderRequest
	27, // 43: rungar.v1.RungarService.EnableProvider:input_type -> rungar.v1.EnableProviderRequest
	31, // 44: rungar.v1.RungarService.ListRunners:input_type -> rungar.v1.ListRunnersRequest
	33, // 45: rungar.v1.RungarService.DeleteRunner:input_type -> rungar.v1.DeleteRunnerRequest
	35, // 46: rungar.v1.RungarService.ListEvents:input_type -> rungar.v1.ListEventsRequest
	6,  // 47: rungar.v1.RungarService.GetStatus:output_type -> rungar.v1.DaemonStatus
	10, // 48: rungar.v1.RungarService.ListScaleSets:output_type -> rungar.v1.ListScaleSetsResponse
	12, // 49: rungar.v1.RungarService.GetScaleSet:output_type -> rungar.v1.ScaleSet
	18, // 50: rungar.v1.RungarService.DeleteScaleSet:output_type -> rungar.v1.DeleteScaleSetResponse
	22, // 51: rungar.v1.RungarService.Reconcile:output_type -> rungar.v1.ReconcileResponse
	12, // 52: rungar.v1.RungarService.PauseScaleSet:output_type -> rungar.v1.ScaleSet
	12, // 53: rungar.v1.RungarService.ResumeScaleSet:output_type -> rungar.v1.ScaleSet
	24, // 54: rungar.v1.RungarService.ListProviders:output_type -> rungar.v1.ListProvidersResponse
	28, // 55: rungar.v1.RungarService.GetProvider:output_type -> rungar.v1.Provider
	28, // 56: rungar.v1.RungarService.DisableProvider:output_type -> rungar.v1.Provider
	28, // 57: rungar.v1.RungarService.EnableProvider:output_type -> rungar.v1.Provider
	32, // 58: rungar.v1.RungarService.ListRunners:output_type -> rungar.v1.ListRunnersResponse
	34, // 59: rungar.v1.RungarService.DeleteRunner:output_type -> rungar.v1.Runner
	36, // 60: rungar.v1.RungarService.ListEvents:output_type -> rungar.v1.ListEventsResponse
	47, // [47:61] is the sub-list for method output_type
	33, // [33:47] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_rungar_v1_rungar_proto_init() }
func file_rungar_v1_rungar_proto_init() {
	if File_rungar_v1_rungar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rungar_v1_rungar_proto_rawDesc), len(file_rungar_v1_rungar_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rungar_v1_rungar_proto_goTypes,
		DependencyIndexes: file_rungar_v1_rungar_proto_depIdxs,
		EnumInfos:         file_rungar_v1_rungar_proto_enumTypes,
		MessageInfos:      file_rungar_v1_rungar_proto_msgTypes,
	}.Build()
	File_rungar_v1_rungar_proto = out.File
	file_rungar_v1_rungar_proto_goTypes = nil
	file_rungar_v1_rungar_proto_depIdxs = nil
}
